export const R=.875,D=1.75,TARGET=D+.004,LEFT=28,RIGHT=260,FLOOR=420,DT=1/120,SUB_DT=1/240,CELL=4,GRID_Y=-16,COLS=58,ROWS=110,CAPACITY=16;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export class ReferenceWorld{
 constructor(particles=[],{passes=64,shock=true}={}){this.passes=passes;this.shock=shock;this.bs=particles.map((b,i)=>({id:b.id??i,x:b.x,y:b.y,vx:b.vx??0,vy:b.vy??0,color:b.color??1,alive:b.alive!==false,sleep:false,quiet:0}));if(new Set(this.bs.map(b=>b.id)).size!==this.bs.length)throw Error('Duplicate particle id');if(this.bs.some(b=>!Number.isInteger(b.color)||b.color<1||b.color>4))throw Error('Colors must be1..4');if(this.bs.some(b=>b.alive&&(![b.x,b.y,b.vx,b.vy].every(Number.isFinite)||Math.abs(b.vx)>60||Math.abs(b.vy)>60)))throw Error('Prototype input requires finite position/velocity and |vx|,|vy|<=60');this.tick=0;this.time=0;this.diagnostics={overflow:0,outsideGrid:0,maxGridDrift:0,maxCorrection:0,zeroPairs:0};}
 grid(){const cells=Array.from({length:COLS*ROWS},()=>[]);for(let i=0;i<this.bs.length;i++){const b=this.bs[i];if(!b.alive)continue;const cx=Math.floor((b.x-LEFT)/CELL),cy=Math.floor((b.y-GRID_Y)/CELL);if(cx<0||cx>=COLS||cy<0||cy>=ROWS){this.diagnostics.outsideGrid++;continue;}const bucket=cells[cy*COLS+cx];bucket.push(i);if(bucket.length>CAPACITY)this.diagnostics.overflow++;}for(const b of cells)b.sort((i,j)=>i-j);return cells;}
 candidates(cells,x,y){const cx=Math.floor((x-LEFT)/CELL),cy=Math.floor((y-GRID_Y)/CELL),out=[];for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const ix=cx+dx,iy=cy+dy;if(ix>=0&&ix<COLS&&iy>=0&&iy<ROWS)out.push(...cells[iy*COLS+ix]);}return out;}
 wakeAll(){for(const b of this.bs)if(b.alive){b.sleep=false;b.quiet=0;}}
 remove(ids){const set=new Set(ids);for(const b of this.bs)if(set.has(b.id))b.alive=false;this.wakeAll();}
 substep(){const n=this.bs.length,prev=this.bs.map(b=>[b.x,b.y]),touched=new Uint8Array(n);for(let i=0;i<n;i++){const b=this.bs[i];if(!b.alive||b.sleep)continue;b.vy=Math.min(60,b.vy+240*SUB_DT);b.x+=b.vx*SUB_DT;b.y+=b.vy*SUB_DT;}
 const gridPos=this.bs.map(b=>[b.x,b.y]),cells=this.grid();if(this.diagnostics.overflow||this.diagnostics.outsideGrid)throw Error('Explicit grid capacity/domain failure');const neighbors=this.bs.map(b=>this.candidates(cells,b.x,b.y));
 for(let pass=0;pass<this.passes;pass++){const next=this.bs.map(b=>[b.x,b.y]);for(let i=0;i<n;i++){const b=this.bs[i];if(!b.alive||b.sleep)continue;let sx=0,sy=0,count=0;for(const j of neighbors[i]){if(j===i)continue;const q=this.bs[j];const dx=b.x-q.x,dy=b.y-q.y,dd=dx*dx+dy*dy;if(dd>=TARGET*TARGET)continue;const dist=Math.sqrt(dd),nx=dist>1e-9?dx/dist:(i<j?-1:1),ny=dist>1e-9?dy/dist:0;if(dist<=1e-9)this.diagnostics.zeroPairs++;const err=TARGET-dist,weight=q.sleep?1:this.shock&&pass>=8?1/(1+Math.exp(dy*1.5)):.5;const rx=(b.x-prev[i][0])-(q.sleep?0:q.x-prev[j][0]),ry=(b.y-prev[i][1])-(q.sleep?0:q.y-prev[j][1]),tangent=-rx*ny+ry*nx,f=clamp(tangent,-.15*err,.15*err)*weight;sx+=nx*err*weight+ny*f;sy+=ny*err*weight-nx*f;count++;}if(count)touched[i]=1;const div=Math.max(1,count*.75);sx/=div;sy/=div;const length=Math.hypot(sx,sy);if(length>.125){sx*=.125/length;sy*=.125/length;}this.diagnostics.maxCorrection=Math.max(this.diagnostics.maxCorrection,Math.hypot(sx,sy));const xx=b.x+sx,yy=b.y+sy;next[i]=[clamp(xx,LEFT+R,RIGHT-R),Math.min(yy,FLOOR-R)];if(next[i][0]!==xx||next[i][1]!==yy||next[i][1]>=FLOOR-R-1e-7)touched[i]=1;}
 for(let i=0;i<n;i++){this.bs[i].x=next[i][0];this.bs[i].y=next[i][1];const drift=Math.hypot(next[i][0]-gridPos[i][0],next[i][1]-gridPos[i][1]);this.diagnostics.maxGridDrift=Math.max(this.diagnostics.maxGridDrift,drift);}if(this.diagnostics.maxGridDrift>1)throw Error('Grid displacement proof violated');}
 for(let i=0;i<n;i++){const b=this.bs[i];if(!b.alive||b.sleep)continue;b.vx=(b.x-prev[i][0])/SUB_DT*(touched[i]?.75:1);b.vy=(b.y-prev[i][1])/SUB_DT*(touched[i]?.75:1);if(b.y>=FLOOR-R-1e-6)b.vx*=.7;}}
 step(){this.substep();this.substep();this.tick++;this.time=this.tick*DT;}
 snapshot(){return {tick:this.tick,time:this.time,bodies:this.bs.map(b=>({...b})),diagnostics:{...this.diagnostics}};}
}
export function audit(particles){let overlap=0,wall=0,minDistance=Infinity;const alive=particles.filter(b=>b.alive!==false);for(let i=0;i<alive.length;i++){const b=alive[i];wall=Math.max(wall,LEFT+R-b.x,b.x-(RIGHT-R),b.y-(FLOOR-R));for(let j=i+1;j<alive.length;j++){const q=alive[j],d=Math.hypot(b.x-q.x,b.y-q.y);minDistance=Math.min(minDistance,d);overlap=Math.max(overlap,D-d);}}return {N:alive.length,overlap,wall,minDistance,finite:alive.every(b=>[b.x,b.y,b.vx??0,b.vy??0].every(Number.isFinite)),passed:alive.every(b=>[b.x,b.y,b.vx??0,b.vy??0].every(Number.isFinite))&&overlap<=.002&&wall<=.002};}
