// Node mocked-DOM protocol/clock/draw smoke. No browser or visual QA is claimed.
import test from 'node:test';
import assert from 'node:assert/strict';
import { createSimulationRuntime } from '../simulation-worker.mjs';
test('original UI boots through real worker runtime: start/drop/fullsync/highlight/restart/stale messages',async()=>{
 let wall=0,timerId=0,rafId=0;const timers=new Map(),rafs=new Map(),elements=new Map(),listeners=new Map();
 const old={};for(const k of['document','window','Worker','location','localStorage','matchMedia','requestAnimationFrame','cancelAnimationFrame','devicePixelRatio','performance'])old[k]=globalThis[k];
 class Context{constructor(){this.polygons=0;this.fills=[];}setTransform(){}fillRect(){}clearRect(){}save(){}restore(){}translate(){}scale(){}beginPath(){}moveTo(){}lineTo(){}closePath(){this.polygons++;}rect(){}clip(){}fill(){this.fills.push(this.fillStyle);}drawImage(){}}
 class Element{constructor(id){this.id=id;this.dataset={};this.style={};this.textContent='';this.hidden=false;this.open=false;this.width=id.startsWith('next')?192:576;this.height=id.startsWith('next')?128:864;this.ctx=new Context();this.handlers=new Map();this.classList={add(){},remove(){},toggle(){}};this.tagName=id.includes('Canvas')?'CANVAS':'BUTTON';}addEventListener(t,f){this.handlers.set(t,f);}setAttribute(k,v){this[k]=v;}getContext(){return this.ctx;}getBoundingClientRect(){return{width:288,height:432};}focus(){document.activeElement=this;}showModal(){this.open=true;}close(){this.open=false;}closest(){return elements.get('settingsDialog');}setPointerCapture(){}}
 const get=id=>{if(!elements.has(id))elements.set(id,new Element(id));return elements.get(id);};
 const buttons=['left','right','rotate','down','drop'].map(action=>{const b=get('control-'+action);b.dataset.action=action;return b;});
 const dialogs=['settingsDialog','helpDialog','restartDialog'].map(get),storage=new Map([['grainform:0.4.5:best','999']]);
 let instance;
 class FakeWorker{constructor(){instance=this;this.runtime=createSimulationRuntime({now:()=>wall,setTimer:(fn,delay)=>{const id=++timerId;timers.set(id,{fn,at:wall+delay});return id;},clearTimer:id=>timers.delete(id),post:message=>this.onmessage?.({data:structuredClone(message)})});}postMessage(data){this.runtime.receive(structuredClone(data));}}
 const advance=target=>{let n=0;while(timers.size){const[id,t]=[...timers].sort((a,b)=>a[1].at-b[1].at)[0];if(t.at>target+1e-7)break;if(++n>10000)throw Error('Unbounded worker callbacks');timers.delete(id);wall=Math.max(wall,t.at);t.fn();}wall=Math.max(wall,target);};
 const draw=()=>{const entry=rafs.entries().next().value;if(entry){rafs.delete(entry[0]);entry[1](wall);}};
 try{
  globalThis.document={getElementById:get,querySelectorAll:selector=>selector==='#touchControls button'?buttons:selector==='dialog'?dialogs:selector==='dialog[open]'?dialogs.filter(d=>d.open):[],createElement:()=>new Element('cache'),documentElement:{classList:{toggle(){}}},body:{dataset:{}},hidden:false,addEventListener:(n,f)=>listeners.set(n,f),activeElement:null};
  globalThis.window={addEventListener:(n,f)=>listeners.set(n,f)};globalThis.Worker=FakeWorker;globalThis.location={search:'?qa&seed=1',reload(){}};globalThis.localStorage={getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v)};globalThis.matchMedia=()=>({matches:false});globalThis.devicePixelRatio=1;globalThis.requestAnimationFrame=f=>{const id=++rafId;rafs.set(id,f);return id;};globalThis.cancelAnimationFrame=id=>rafs.delete(id);Object.defineProperty(globalThis,'performance',{value:{now:()=>wall},configurable:true});
  await import('../app.mjs?ui-grid-boot');const qa=window.grainformQA;assert.equal(qa.ready,true);assert.equal(qa.version,'0.4.6');assert.equal(qa.read().storage.best,0);assert.equal(storage.get('grainform:0.4.5:best'),'999');draw();
  await qa.command('start');advance(1000);await qa.command('snapshot');draw();assert.equal(qa.read().tick,120);assert.equal(qa.read().worker.steps,120);assert.equal(qa.read().worker.debtSteps,0);
  await qa.command('drop');await qa.command('snapshot');draw();assert.equal(qa.read().grains,676);assert.equal(qa.snapshot.bodies.length,676);assert.equal(qa.read().renderer.liveCount,676);assert.equal(qa.read().renderer.countsConserved,true);assert.deepEqual(qa.snapshot.bodies,instance.runtime.game.world.bodies());
  qa.resync();draw();assert.equal(qa.read().grains,676);assert.equal(qa.read().renderer.liveCount,676);
  const oldEpoch=instance.runtime.epoch;await qa.command('restart',{seed:1});draw();assert.equal(qa.read().grains,0);assert.equal(qa.read().renderer.liveCount,0);assert.equal(qa.read().highlightCount,0);for(const type of['fatal','visibility','ack','ready'])instance.onmessage({data:{type,epoch:oldEpoch,id:999,state:'paused',hidden:true,message:'old failure'}});assert.equal(qa.read().failed,false);assert.equal(qa.read().state,'playing');
  const g=instance.runtime.game,specs=Array.from({length:132},(_,col)=>({id:col,row:0,col,color:1}));assert.equal(g.world.addMany(specs).accepted,true);g.pendingClear=[specs.map(p=>p.id)];g.clearTimer=.2;g.emit('clear-start',{count:132});await qa.command('snapshot');const screen=get('gameCanvas').ctx;const fillStart=screen.fills.length;draw();assert.equal(qa.read().highlightCount,132);assert.ok(screen.fills.slice(fillStart).includes('#fffce8'));
  const clearStart=wall;advance(clearStart+200);await qa.command('snapshot');const afterFill=screen.fills.length;draw();assert.equal(g.world.tick,0);assert.equal(g.gameTick,24);assert.equal(qa.read().highlightCount,0);assert.equal(qa.read().grains,0);assert.ok(!screen.fills.slice(afterFill).includes('#fffce8'));assert.equal(qa.read().renderer.liveCount,0);
  const fixtureEpoch=instance.runtime.epoch;const fixtureAck=await qa.bridge();assert.equal(fixtureAck.applied,true);assert.equal(instance.runtime.epoch,fixtureEpoch+1);assert.equal(qa.read().grains,172);assert.equal(qa.read().qaFixture.artificial,true);assert.equal(qa.read().pendingInputs,0);assert.match(get('clockNotice').textContent,/人工QA/);draw();assert.equal(qa.read().lastDrawBodySequence,qa.read().bodySequence);
  const fixtureStart=wall;advance(fixtureStart+16*1000/120);await qa.command('snapshot');draw();assert.equal(qa.read().lastDrawHighlightCount,132);assert.equal(qa.read().grains,172);advance(fixtureStart+40*1000/120);await qa.command('snapshot');draw();assert.equal(qa.read().lastDrawHighlightCount,0);assert.equal(qa.read().grains,40);assert.equal(qa.read().renderer.liveCount,40);assert.equal(qa.read().renderer.countsConserved,true);
  assert.ok(rafs.size<=1);instance.runtime.dispose();
 }finally{for(const k of Object.keys(old)){if(k==='performance')Object.defineProperty(globalThis,k,{value:old[k],configurable:true});else if(old[k]===undefined)delete globalThis[k];else globalThis[k]=old[k];}}
});
