import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';const{createRequire}=await import('node:module');const{chromium}=process.env.GRAINFORM_PLAYWRIGHT_MODULE?await import(process.env.GRAINFORM_PLAYWRIGHT_MODULE):createRequire(import.meta.url)('playwright');
const root=new URL('./',import.meta.url).pathname,E=path.join(root,'evidence');const b=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true});const ctx=await b.newContext({viewport:{width:1100,height:850}}),page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
await page.route('http://grain.local/**',async route=>{const u=new URL(route.request().url()),n=u.pathname==='/'?'index.html':u.pathname.slice(1);try{await route.fulfill({body:fs.readFileSync(path.join(root,n)),contentType:n.endsWith('.mjs')?'text/javascript':n.endsWith('.css')?'text/css':n.endsWith('.png')?'image/png':'text/html'})}catch{await route.fulfill({status:404,body:'missing'})}});
await page.addInitScript(()=>{window.trace=[];window.rawAcks=[];const Native=window.Worker;window.Worker=class extends Native{constructor(...a){super(...a);window.realWorker=this;this.addEventListener('message',({data:d})=>{if(d.type==='snapshot'){const s=d.snapshot;window.trace.push({wall:performance.now(),epoch:d.epoch,seq:d.seq,phase:s.phase,pieceId:s.pieceId,tick:s.tick,live:s.bodyCount,active:s.activeCount,added:s.added,cleared:s.rawCleared,token:s.presentationToken,presented:s.presentedToken,diagnostics:d.diagnostics});}if(d.type==='ack')window.rawAcks.push(d);});}};window.raw=async(data)=>{const id=100000+window.rawAcks.length;realWorker.postMessage({type:'command',id,...data});const start=performance.now();while(!window.rawAcks.some(a=>a.id===id)){if(performance.now()-start>2000)throw Error('ACK timeout');await new Promise(r=>setTimeout(r,5));}return window.rawAcks.find(a=>a.id===id)};});
const read=()=>page.evaluate(()=>grainformQA.read()),cmd=(name,value)=>page.evaluate(([n,v])=>grainformQA.command(n,v),[name,value]),wait=(fn,timeout=10000)=>page.waitForFunction(fn,null,{timeout});const results=[];
async function waitForNewPiece(epoch,afterPieceId){const handle=await page.waitForFunction(({epoch,afterPieceId})=>{const q=grainformQA.read();return q.worker.epoch===epoch&&q.phase==='falling'&&q.pieceId>afterPieceId&&q.active?q:false},{epoch,afterPieceId},{timeout:10000});return handle.jsonValue();}

try{
 await page.goto('http://grain.local/?qa&seed=1');await wait(()=>window.grainformQA?.ready);const boot=await read();await page.waitForTimeout(250);assert.equal((await read()).grains,0);results.push({case:'boot',boot});
 await cmd('start');const before=await read(),start=performance.now();await cmd('drop');await wait(()=>grainformQA.read().phase==='falling'&&grainformQA.read().pieces===1);const first=await read();results.push({case:'normal-first-real-wall',wallMs:performance.now()-start,first});assert.equal(first.grains,2304);assert.equal(first.failed,false);const stale=await page.evaluate(({epoch,pieceId})=>raw({name:'move',value:48,epoch,pieceId}),{epoch:before.worker.epoch,pieceId:before.pieceId});assert.equal(stale.reason,'stale-piece');
 await page.screenshot({path:path.join(E,'first-settled-ui.png')});
 await cmd('drop');await page.waitForTimeout(100);await cmd('pause');const paused=await read();await page.waitForTimeout(250);assert.equal((await read()).tick,paused.tick);await cmd('resume');await wait(()=>grainformQA.read().phase==='falling');results.push({case:'pause-resume-settling',paused,after:await read()});
 await cmd('qa-bridge');await wait(()=>grainformQA.read().phase==='flash');const flash=await page.evaluate(()=>grainformQA.snapshot);assert.equal(flash.activeCount,0);assert.equal(flash.clearIds.length,232);assert.equal(flash.presentedToken,flash.presentationToken);await cmd('pause');await page.screenshot({path:path.join(E,'clear-flash-ui.png')});await cmd('resume');await wait(()=>grainformQA.read().phase==='falling');const cleared=await page.evaluate(()=>grainformQA.snapshot);assert.equal(cleared.bodyCount,40);assert.equal(cleared.rawCleared,232);assert(cleared.bodies.every(p=>p.y===419.5));results.push({case:'full-clear-support-recovery',flashCount:flash.clearIds.length,cleared});
 const restartAck=await cmd('restart',{seed:1});await waitForNewPiece(restartAck.epoch,0);await page.keyboard.down('ArrowRight');const heldDropAck=await cmd('drop');assert(heldDropAck.applied);const held=await waitForNewPiece(heldDropAck.epoch,heldDropAck.pieceId);await page.waitForTimeout(300);const heldAfter=await read();assert.equal(heldAfter.worker.epoch,held.worker.epoch);assert.equal(heldAfter.pieceId,held.pieceId);assert(heldAfter.active,'new falling piece must still exist');assert.equal(heldAfter.active.x,held.active.x);assert.equal(heldAfter.heldInputs,0);await page.keyboard.up('ArrowRight');results.push({case:'held-next-piece',held,heldAfter,dropPieceId:heldDropAck.pieceId});
 const old=await read();await cmd('restart',{seed:3});const bad=await page.evaluate(({epoch,pieceId})=>raw({name:'drop',epoch,pieceId}),{epoch:old.worker.epoch,pieceId:old.pieceId});assert.equal(bad.reason,'stale-round');assert.equal((await read()).grains,0);results.push({case:'restart-stale-epoch',reason:bad.reason});
 await cmd('qa-bridge',{fixture:'capacity'});await cmd('drop');await wait(()=>grainformQA.read().state==='over');assert.equal((await read()).grains,0);results.push({case:'atomic-capacity',data:await read()});
 const trace=await page.evaluate(()=>window.trace);for(const s of trace){assert.equal(s.live+s.cleared,s.added);if(s.phase==='flash'){assert.equal(s.active,0);assert.equal(s.token,s.presented)}}assert.deepEqual(errors,[]);fs.writeFileSync(path.join(E,'browser-trace.json'),JSON.stringify(trace));fs.writeFileSync(path.join(E,'browser-smoke.json'),JSON.stringify({pass:true,results,errors},null,2));console.log(JSON.stringify({pass:true,cases:results.map(r=>r.case),wallFirstMs:results.find(r=>r.case==='normal-first-real-wall').wallMs}));
}catch(e){fs.writeFileSync(path.join(E,'browser-smoke.json'),JSON.stringify({pass:false,error:String(e),stack:e.stack,results,errors,current:await read().catch(()=>null)},null,2));await page.screenshot({path:path.join(E,'browser-failure.png')}).catch(()=>{});console.error(e);process.exitCode=1}finally{await b.close()}
