import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {World,CFG} from './ca-world.mjs';
import {FrameWorld} from './ca-frame-world.mjs';
const results=[];
function run(name,fn){const detail=fn();results.push({name,passed:true,...detail});console.log(`PASS ${name}`)}
function stateHash(w){const h=createHash('sha256');for(const [k,v]of Object.entries(w)){h.update(k);if(ArrayBuffer.isView(v))h.update(Buffer.from(v.buffer,v.byteOffset,v.byteLength));else if(typeof v!=='function')h.update(JSON.stringify(v instanceof Set?[...v]:v)??'undefined')}return h.digest('hex')}
function unchanged(w,fn,error){const before=stateHash(w);assert.throws(fn,error);assert.equal(stateHash(w),before,'rejected operation changed state')}
function audit(w){let count=0;const found=new Set();for(let q=0;q<w.grid.length;q++)if(w.grid[q]){const i=w.grid[q]-1;assert(w.live[i]);assert.equal(w.cell(w.x[i],w.y[i]),q);assert(!found.has(i));found.add(i);count++}assert.equal(count,w.count);assert.equal(w.n,w.count+w.freeCount);assert(w.n<=w.live.length);const free=new Set(w.freeSlots.subarray(0,w.freeCount));assert.equal(free.size,w.freeCount);for(let i=0;i<w.n;i++){assert.equal(!!w.live[i],found.has(i));assert.equal(!w.live[i],free.has(i));if(w.live[i])assert.equal(w.slotOf(w.idAt(i)),i)}}
run('320 admissions and removals keep storage bounded',()=>{const w=new FrameWorld(),points=Array.from({length:512},(_,i)=>({x:10+i%32,y:10+Math.floor(i/32)})),seen=new Set();let first;
 for(let batch=0;batch<320;batch++){assert.equal(w.admit(points,batch%8,batch,45),512);assert.equal(w.n,512);assert.equal(w.count,512);const snapshot=w.snapshot();if(!first)first=snapshot.map(p=>p.id);for(const p of snapshot){assert(!seen.has(p.id));seen.add(p.id);assert.equal(w.vy[w.slotOf(p.id)],45);assert.equal(w.credit[w.slotOf(p.id)],0);assert.equal(w.pathN[w.slotOf(p.id)],0);assert.equal(w.frameN[w.slotOf(p.id)],0)}if(batch===0||batch===319)audit(w);w.remove(snapshot.map(p=>p.id));assert.equal(w.count,0);assert.equal(w.freeCount,512)}
 w.admit(points,7,321,0);const before=stateHash(w);assert.throws(()=>w.remove([w.snapshot()[0].id,first[0]]),/missing-ID/);assert.equal(stateHash(w),before);audit(w);return{cycles:320,cumulativeBirths:320*512,capacity:w.live.length,peakSlots:w.n,live:w.count}
});
run('stale, duplicate and malformed removals are atomic',()=>{const w=new FrameWorld();w.admit([{x:10,y:10},{x:12,y:10}],1,1,480);w.stepFrame();w.remove([0]);w.admit([{x:20,y:20}],2,2);const fresh=w.idAt(0);assert.notEqual(fresh,0);for(const ids of [[1,0],[1,fresh,fresh],[1,NaN],[1,-1],[1,1.5],[1,Number.MAX_SAFE_INTEGER+1],[1,'1']])unchanged(w,()=>w.remove(ids),/missing-ID|duplicate-ID/);assert.throws(()=>w.positionAt(0,.5),/missing-ID/);assert(!w.has(0));assert(w.has(fresh));assert.deepEqual(w.frameIds,[1]);audit(w)});
run('invalid admissions preserve free list, identity, state and wake data',()=>{const w=new FrameWorld();w.admit([{x:10,y:10},{x:12,y:10}],1,1);w.remove([0]);for(const points of [[{x:11,y:10},{x:12,y:10}],[{x:11,y:10},{x:-1,y:10}],[{x:11,y:10},{x:11,y:10}]])unchanged(w,()=>w.admit(points,2,2),/admission/);unchanged(w,()=>w.admit([{x:11,y:10}],2n,2),/admission-fields/);unchanged(w,()=>w.admit([{x:11,y:10}],2,2,Infinity),/admission-fields/);audit(w)});
run('new and reused births have no old interpolation, motion or stamps',()=>{for(const Type of [World,FrameWorld]){const w=new Type();w.admit([{x:10,y:10}],1,1,480);assert.deepEqual(w.positionAt(0,0),[10.5,10.5]);if(w.stepFrame)w.stepFrame();else w.step();assert(w.pathN[0]>1);if(w.stepFrame)assert(w.frameN[0]>1);w.credit[0]=7.75;w.remove([0]);w.admit([{x:100,y:200}],2,2,0);const id=w.idAt(0);assert.equal(id,CFG.width*CFG.height);assert.equal(w.vy[0],0);assert.equal(w.credit[0],0);assert.equal(w.pathN[0],0);assert.notEqual(w.pathStamp[0],w.tick);assert.notEqual(w.moveStamp[0],w.tick);assert.equal(w.lastMoved[0],w.tick);for(const alpha of [0,.25,.5,.75,1])assert.deepEqual(w.positionAt(id,alpha),[100.5,200.5]);assert.throws(()=>w.positionAt(0,.5),/missing-ID/);assert(w.pathX.subarray(0,18).every(v=>v===0));if(w.stepFrame){assert.equal(w.frameN[0],0);assert(w.frameX.subarray(0,69).every(v=>v===0));w.stepFrame();assert.deepEqual(w.frameIds,[id]);assert.deepEqual(w.positionAt(id,0),[100.5,200.5]);assert.deepEqual(w.positionAt(id,1),[w.x[0]+.5,w.y[0]+.5])}else{w.step();assert.equal(w.y[0],200);assert.equal(w.vy[0],15);assert.equal(w.credit[0],.25)}audit(w)}});
run('live identities and roughness survive unrelated slot reuse',()=>{const w=new FrameWorld();w.admit([{x:10,y:418},{x:100,y:419}],1,1);const id=w.idAt(1),rough=w.roughness(id);for(let j=0;j<20;j++){const dead=w.idAt(0);w.remove([dead]);w.admit([{x:10,y:418}],2,j+2);assert.equal(w.idAt(1),id);assert.equal(w.roughness(id),rough)}let seen;w.audit=(id)=>{seen=id};w.stepFrame();assert.equal(w.idAt(1),id);assert.equal(w.roughness(id),rough);assert.equal(seen,w.idAt(0));assert.notEqual(seen,0);audit(w)});
run('reused occupant direction uses its own fixed identity roughness',()=>{const w=new World();w.admit([{x:10,y:10},{x:10,y:11},{x:11,y:11}],1,1);const classes=new Set();for(let generation=0;generation<32;generation++){const id=w.idAt(0),rough=w.roughness(id);classes.add(rough);assert.equal(w.direction(0,1,false)?.dist,rough===2?2:undefined);assert.equal(w.roughness(id),rough);w.remove([id]);w.admit([{x:10,y:10}],1,generation+2)}assert.equal(classes.size,2);audit(w)});
run('handle precision exhaustion rejects before any birth',()=>{const w=new World(),C=w.live.length;w.admit([{x:10,y:10},{x:12,y:10}],1,1);w.remove([0,1]);const i=w.freeSlots[w.freeCount-1];w.identity[i]=Math.floor((Number.MAX_SAFE_INTEGER-i)/C)*C+i;unchanged(w,()=>w.admit([{x:10,y:10},{x:12,y:10}],2,2),/identity-exhausted/)});
fs.writeFileSync(new URL('./evidence/slot-merge-tests.json',import.meta.url),JSON.stringify({passed:true,results},null,2)+'\n');
