import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {FrameWorld as Baseline,CFG} from './validation-reference/frame-world.mjs';
import {FrameWorld as Candidate} from './ca-frame-world.mjs';
const fixtures=JSON.parse(fs.readFileSync(new URL('./validation-reference/fixtures.json',import.meta.url)));
const original=JSON.parse(fs.readFileSync(new URL('./validation-reference/expected.json',import.meta.url)));
const two=JSON.parse(fs.readFileSync(new URL('./validation-reference/expected.json',import.meta.url)));
const a=new Baseline(),b=new Candidate(),out=[];let comparedFrames=0,comparedRuleTicks=0;const trajectory=createHash('sha256');
const cells=(shape,x,y)=>shape.flatMap(([sx,sy])=>Array.from({length:576},(_,i)=>({x:x+sx*24+i%24,y:y+sy*24+Math.floor(i/24)})));
function bytes(w,key){const v=w[key];return Buffer.from(v.buffer,v.byteOffset,v.byteLength)}
function compareState(){for(const k of ['grid','x','y','live','color','batch','vy','credit'])assert(bytes(a,k).equals(bytes(b,k)),`${k} mismatch at tick ${a.tick}`);for(const k of ['n','count','tick','time','seed','noMoveSweeps','pendingInbound','lastMoveTick','presentedTick'])assert.equal(a[k],b[k],k);for(const k of ['last','metrics','dirty'])assert.deepEqual(a[k],b[k],k);assert.deepEqual([...a.chunks],[...b.chunks]);assert.equal(a.ready(),b.ready())}
function compareFrame(){compareState();for(const k of ['frameN','frameX','frameY','framePhase','frameStamp'])assert(bytes(a,k).equals(bytes(b,k)),`${k} mismatch at frame ${a.frame}`);for(const k of ['frame','framePending','frameIds','frameDirty','frameLast'])assert.deepEqual(a[k],b[k],k);for(const id of a.frameIds)for(const alpha of [0,.125,.5,.875,1])assert.deepEqual(a.positionAt(id,alpha),b.positionAt(id,alpha));trajectory.update(bytes(b,'grid'));trajectory.update(bytes(b,'frameX'));trajectory.update(bytes(b,'frameY'));trajectory.update(bytes(b,'framePhase'));comparedFrames++}
function fall(spec){for(const w of [a,b])w.pendingInbound++;const shape=spec.shape,width=(1+Math.max(...shape.map(p=>p[0])))*24,x=Math.floor((232-width)/2);let y=0,v=0,credit=0,ticks=0;const legal=yy=>cells(shape,x,yy).every(p=>p.y<420&&!a.grid[a.cell(p.x,p.y)]);assert(legal(0));for(;;){a.step();b.step();compareState();comparedRuleTicks++;v=Math.min(480,v+15);credit+=v/60;ticks++;let land=false;while(credit>=1){if(!legal(y+1)){land=true;break}y++;credit--}if(land){const points=cells(shape,x,y);for(const w of [a,b]){assert(!w.ready());w.admit(points,spec.color,spec.number,v);w.pendingInbound--}compareState();return{x,y,v,ticks,shape}}assert(ticks<600)}}
function settle(label){let steps=0;while(!a.ready()&&steps<180){a.stepFrame();b.stepFrame();compareFrame();assert(!a.ready());a.completePresentation();b.completePresentation();assert.equal(a.ready(),b.ready());steps++}assert(a.ready(),`${label} failed to settle`);assert.deepEqual(a.snapshot(),b.snapshot());return{label,steps,count:b.count,hash:createHash('sha256').update(JSON.stringify(b.snapshot())).digest('hex')}}
function eligible(w){const visited=new Uint8Array(w.grid.length),ids=[];for(let p=0;p<w.grid.length;p++){if(!w.grid[p]||visited[p])continue;const color=w.color[w.grid[p]-1],q=[p],component=[];visited[p]=1;let left=false,right=false;for(let j=0;j<q.length;j++){const c=q[j],x=c%232,y=Math.floor(c/232);component.push(w.grid[c]-1);left||=x===0;right||=x===231;for(const [xx,yy]of [[x-1,y],[x+1,y],[x,y-1],[x,y+1]]){if(xx<0||xx>=232||yy<0||yy>=420)continue;const n=xx+yy*232,v=w.grid[n];if(v&&!visited[n]&&w.color[v-1]===color){visited[n]=1;q.push(n)}}}if(left&&right)ids.push(...component)}return ids}
for(let n=0;n<6;n++){const f=fixtures[n].piece,pose=fall({shape:f.shape,color:f.color,number:n+1}),result=settle(`batch${n+1}`);assert.equal(result.steps,original.results[n].steps);assert.deepEqual(b.snapshot(),original.results[n].final);if(n<2){assert.equal(result.steps,two.results[n].steps);assert.deepEqual(b.snapshot(),two.results[n].final)}out.push({...result,pose});console.log(JSON.stringify(out.at(-1)))}
for(let j=0;j<60;j++){a.step();b.step();a.completePresentation();b.completePresentation();compareState()}
const clearIds=eligible(a);assert.deepEqual(clearIds,original.clear.ids);a.remove(clearIds);b.remove(clearIds);compareState();if(clearIds.length){const result=settle('gameClear');assert.deepEqual(b.snapshot(),original.clear.recovery.final);out.push(result)}
const cutIds=a.snapshot().filter(p=>p.x>=82&&p.x<150&&p.y>=365&&p.y<375).map(p=>p.id);assert.deepEqual(cutIds,original.cut.ids);a.remove(cutIds);b.remove(cutIds);compareState();const result=settle('supportCut');assert.deepEqual(b.snapshot(),original.cut.final);out.push(result);
fs.writeFileSync(new URL('./evidence/slot-wake-parity.json',import.meta.url),JSON.stringify({passed:true,comparedFrames,comparedRuleTicks,trajectoryHash:trajectory.digest('hex'),clearCount:clearIds.length,cutCount:cutIds.length,results:out},null,2)+'\n');
console.log('PASS exact six-batch, clear and support-cut parity; two-batch checkpoints match frozen evidence');
