import test from 'node:test';import assert from 'node:assert/strict';
import {createSimulationRuntime} from '../../simulation-worker.mjs';import {decodeSnapshotWire} from '../../snapshot-transport.mjs';
function harness(){let now=0,timer=0;const out=[],packets=[];const r=createSimulationRuntime({now:()=>now,timeOrigin:0,setTimer:()=>++timer,clearTimer:()=>{},post:(p,transfer=[])=>out.push(structuredClone(p,{transfer}))});let id=0;
 const command=(name,value)=>r.receive({type:'command',id:++id,name,value,epoch:r.epoch,pieceId:r.game?.pieceId});
 const receipt=e=>r.receive({type:'snapshot-received',transportId:e.transportId,epoch:e.epoch});
 const drain=(hold=()=>false)=>{while(out.length){const e=out.shift();if(e.type!=='snapshot-wire')continue;const p=decodeSnapshotWire(e);packets.push(p);if(hold(p))return{e,p};receipt(e);}return null;};
 const step=(ms=1000/60)=>{now+=ms;r.pump();};
 const firstMaterial=()=>{r.receive({type:'init',seed:2026});drain();command('start');drain();command('drop');drain();let held;for(let i=0;i<100&&!held;i++){step();held=drain(p=>p.presentationGroups.length>0);}assert(held);return held;};return{r,out,packets,command,receipt,drain,step,firstMaterial};}
test('one held material wire permits exactly the remaining group; no ACK or extra wire is fabricated',()=>{const h=harness(),held=h.firstMaterial(),before=h.r.game.gameTick;assert.equal(h.r.stats().pendingMaterialFrames,1);assert(h.r.stats().transportOverlapAllowed);h.step(200);const s=h.r.stats();assert.equal(h.r.game.gameTick,before+4);assert.equal(s.pendingMaterialFrames,2);assert.equal(s.transportQueuedOwners,1);assert.equal(s.transportInFlightCount,1);assert.equal(s.presentedToken,0);assert.equal(s.transportOverlapSteps,4);assert(s.transportInFlightBytes<=64*1024*1024);h.step(200);assert.equal(h.r.game.gameTick,before+4);h.receipt(held.e);const next=h.drain(p=>p.presentationGroups.length>0);assert(next);assert.equal(next.p.seq,held.p.seq+1);assert.equal(next.p.baseSeq,held.p.seq);assert.equal(next.p.bodyPatch.previousRevision,held.p.bodyPatch.revision);h.r.dispose();});
test('unreceived epoch baseline and full resync block overlap',()=>{const h=harness();h.r.receive({type:'init',seed:2026});const first=h.drain(()=>true);h.command('start');h.step(200);assert.equal(h.r.game.gameTick,0);assert.equal(h.r.stats().epochFullReceiptReady,false);h.receipt(first.e);h.drain();h.command('drop');h.drain();let held;for(let i=0;i<100&&!held;i++){h.step();held=h.drain(p=>p.presentationGroups.length>0);}assert(held);const tick=h.r.game.gameTick;h.r.receive({type:'resync',epoch:h.r.epoch});h.step(200);assert.equal(h.r.game.gameTick,tick);assert.equal(h.r.stats().transportOverlapAllowed,false);h.receipt(held.e);const owned=h.drain(()=>true);assert.equal(owned.p.mode,'delta');assert.equal(owned.p.baseSeq,held.p.seq);assert.equal(owned.p.bodyPatch.previousRevision,held.p.bodyPatch.revision);h.receipt(owned.e);const full=h.drain(()=>true);assert.equal(full.p.mode,'full');assert.equal(full.p.seq,owned.p.seq+1);assert.equal(full.p.bodyPatch.revision,owned.p.bodyPatch.revision);h.step(200);assert.equal(h.r.game.gameTick,tick);h.r.dispose();});
test('pause/hidden freeze; restart keeps old wire credit and requires new full before delta',()=>{const h=harness(),held=h.firstMaterial(),tick=h.r.game.gameTick;h.command('pause');h.step(200);assert.equal(h.r.game.gameTick,tick);h.r.receive({type:'visibility',epoch:h.r.epoch,hidden:true});h.command('resume');h.step(200);assert.equal(h.r.game.gameTick,tick);h.r.receive({type:'visibility',epoch:h.r.epoch,hidden:false});h.command('restart',{seed:2026});const epoch=h.r.epoch;h.step(200);assert.equal(h.r.game.gameTick,0);assert.equal(h.r.stats().epochFullReceiptReady,false);assert.equal(h.r.stats().transportInFlightCount,1);h.receipt(held.e);const fresh=h.drain(()=>true);assert.equal(fresh.p.epoch,epoch);assert.equal(fresh.p.mode,'full');assert.equal(fresh.p.seq,1);assert.equal(fresh.p.presentationGroups.length,0);h.step(200);assert.equal(h.r.game.gameTick,0);h.r.dispose();});

test('resync arriving with only one group closes spare compute credit immediately',()=>{const h=harness(),held=h.firstMaterial(),tick=h.r.game.gameTick;h.r.receive({type:'resync',epoch:h.r.epoch});h.step(200);assert.equal(h.r.game.gameTick,tick);assert.equal(h.r.stats().pendingMaterialFrames,1);h.receipt(held.e);const full=h.drain(()=>true);assert.equal(full.p.mode,'full');h.step(200);assert.equal(h.r.game.gameTick,tick);h.r.dispose();});
test('resync flushes retained partial group before full without losing consumed body changes',async()=>{const {GridBodyStore}=await import('../../app.mjs');const h=harness(),held=h.firstMaterial();h.step();assert.equal(h.r.stats().compositeBuildingFrames,1);const tick=h.r.game.gameTick;h.r.receive({type:'resync',epoch:h.r.epoch});h.step(200);assert.equal(h.r.game.gameTick,tick);h.receipt(held.e);const partial=h.drain(()=>true);assert.equal(partial.p.mode,'delta');assert.equal(partial.p.presentationGroups[0].tickCount,1);assert.equal(partial.p.baseSeq,held.p.seq);h.receipt(partial.e);const full=h.drain(()=>true);assert.equal(full.p.mode,'full');assert.equal(full.p.seq,partial.p.seq+1);const store=new GridBodyStore();for(const packet of h.packets)assert(store.accept(packet).accepted);const normalize=b=>({id:b.id,x:b.x,y:b.y,color:b.color,sleep:b.sleep});const sorted=a=>a.sort((a,b)=>a.id-b.id);assert.deepEqual(sorted(store.array().map(normalize)),sorted([...h.r.game.world.cache.values()].map(normalize)));assert.equal(store.revision,h.r.game.world.revision);assert.equal(h.r.stats().pendingMaterialFrames,2);h.r.dispose();});
