import { runAnalyticalGPU, runLocalGPU } from './physical-gates.mjs';
import {createGPUWorld,GPU_CONTRACT}from'./gpu-solver.mjs';import{ReferenceWorld,audit}from'./reference.mjs';import{fixture}from'./fixtures.mjs';
const $=id=>document.getElementById(id),gl=$('compute').getContext('webgl2',{antialias:false,alpha:false,preserveDrawingBuffer:false});let running=false,last=null;const results=[];
function show(value){last=value;$('status').textContent=JSON.stringify(value,null,2);return value;}
function draw(canvas,particles){const ctx=canvas.getContext('2d');ctx.setTransform(2,0,0,2,0,0);ctx.fillStyle='#0c1315';ctx.fillRect(0,0,288,432);ctx.fillStyle='#4e6258';ctx.fillRect(24,0,4,424);ctx.fillRect(260,0,4,424);ctx.fillRect(24,420,240,4);const colors=['','#eac370','#4fc0b3','#d378a3','#789fef'];for(const b of particles){if(!b.alive)continue;ctx.beginPath();for(let i=0;i<8;i++){const a=Math.PI/8+i*Math.PI/4,x=b.x+.87*Math.cos(a),y=b.y+.87*Math.sin(a);if(i)ctx.lineTo(x,y);else ctx.moveTo(x,y);}ctx.closePath();ctx.fillStyle=colors[b.color];ctx.fill();}}
function comparison(a,b){let maxPosition=0,maxVelocity=0;const identities=a.length===b.length&&a.every((x,i)=>x.id===b[i].id&&x.color===b[i].color&&x.alive===b[i].alive);for(let i=0;i<Math.min(a.length,b.length);i++){if(!a[i].alive||!b[i].alive)continue;maxPosition=Math.max(maxPosition,Math.abs(a[i].x-b[i].x),Math.abs(a[i].y-b[i].y));maxVelocity=Math.max(maxVelocity,Math.abs(a[i].vx-b[i].vx),Math.abs(a[i].vy-b[i].vy));}return{identities,maxPosition,maxVelocity,cpuPrecision:'Float64',gpuPrecision:'Float32',bitEquivalent:false};}
async function fence(timeoutMs=120000){const sync=gl.fenceSync(gl.SYNC_GPU_COMMANDS_COMPLETE,0);if(!sync)throw Error('GPU fence unavailable');gl.flush();const start=performance.now();try{while(true){const s=gl.clientWaitSync(sync,0,0);if(s===gl.CONDITION_SATISFIED||s===gl.ALREADY_SIGNALED)return performance.now()-start;if(s===gl.WAIT_FAILED)throw Error('GPU fence failed');if(performance.now()-start>timeoutMs)throw Error('GPU completion timed out');await new Promise(r=>setTimeout(r,4));}}finally{gl.deleteSync(sync);}}
async function runCase(name='pair',{steps=10,passes=64,shock=true}={}){if(running)throw Error('Probe already running');if(!Number.isInteger(steps)||steps<1||steps>240)throw Error('steps must be1..240');running=true;let gpu;try{const p=fixture(name),cpu=new ReferenceWorld(p,{passes,shock});gpu=await createGPUWorld(gl,p,{passes,shock});const initial=gpu.readback();const rows=[];let submissionMs=0,waitMs=0,readbackMs=0,cpuMs=0;for(let i=1;i<=steps;i++){let t=performance.now();cpu.step();cpuMs+=performance.now()-t;t=performance.now();gpu.step();submissionMs+=performance.now()-t;if(i===1||i===10||i===30||i===steps){waitMs+=await fence();t=performance.now();const read=gpu.readback();readbackMs+=performance.now()-t;const row={step:i,gpuAudit:audit(read.particles),cpuAudit:audit(cpu.bs),compare:comparison(read.particles,cpu.bs),diagnostics:read.diagnostics};rows.push(row);draw($('gpuView'),read.particles);draw($('cpuView'),cpu.bs);if(read.diagnostics.invalid)break;await new Promise(r=>setTimeout(r,0));}}
 const result={scope:'Actual GPU physics readback against CPU reference; not game FPS or hardware certification',name,requestedSteps:steps,completedSteps:gpu.steps,passes,shock,initial:audit(initial.particles),rows,timing:{cpuReferenceMs:cpuMs,cpuGPUCommandSubmissionMs:submissionMs,gpuFenceWaitMs:waitMs,readbackMs},passed:rows.every(r=>r.gpuAudit.passed&&r.cpuAudit.passed&&r.compare.identities&&r.compare.maxPosition<=.01&&r.compare.maxVelocity<=.5&&!r.diagnostics.invalid),contract:GPU_CONTRACT,platform:capability};results.push(result);return show(result);}catch(e){show({error:String(e)});throw e;}finally{gpu?.dispose();running=false;}}
async function runOverflow(n=17){if(running)throw Error('Probe already running');running=true;let gpu;try{const p=Array.from({length:n},(_,i)=>({id:i,x:140,y:300,vx:0,vy:0,color:1+i%4,alive:true}));gpu=await createGPUWorld(gl,p,{passes:16});gpu.step();await fence();const r=gpu.readback({includeBuckets:true});return show({scope:'Intentional invalid occupancy fixture, not normal geometry test',N:n,retainedSlots:r.particles.length,overflowDetected:r.diagnostics.overflow,diagnostics:r.diagnostics,passed:n>16?r.diagnostics.overflow&&r.particles.length===n:!r.diagnostics.overflow});}finally{gpu?.dispose();running=false;}}
async function runRemoval(){if(running)throw Error('Probe already running');running=true;let gpu;try{const p=fixture('stack'),cpu=new ReferenceWorld(p);gpu=await createGPUWorld(gl,p,{passes:64});if(typeof gpu.remove!=='function')return show({blocked:'Live GPU removal is not implemented; replacement fixtures are not accepted as removal evidence.'});for(let i=0;i<10;i++){cpu.step();gpu.step();}await fence();const before=gpu.readback();gpu.remove([0]);cpu.remove([0]);for(let i=0;i<30;i++){cpu.step();gpu.step();}await fence();const after=gpu.readback();const falls=after.particles.filter((b,i)=>b.alive&&b.y>before.particles[i].y+.1).length;return show({scope:'Actual live GPU support removal, all particles awake in this stage',beforeN:before.particles.filter(b=>b.alive).length,afterN:after.particles.filter(b=>b.alive).length,falls,audit:audit(after.particles),compare:comparison(after.particles,cpu.bs),diagnostics:after.diagnostics,passed:after.particles.filter(b=>b.alive).length===p.length-1&&falls>0&&audit(after.particles).passed&&audit(cpu.bs).passed&&comparison(after.particles,cpu.bs).identities&&comparison(after.particles,cpu.bs).maxPosition<=.01&&comparison(after.particles,cpu.bs).maxVelocity<=.5&&!after.diagnostics.invalid});}finally{gpu?.dispose();running=false;}}
const debug=gl?.getExtension('WEBGL_debug_renderer_info');const capability={webgl2:!!gl,renderer:gl?(debug?gl.getParameter(debug.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER)):null,userAgent:navigator.userAgent,dpr:devicePixelRatio,hardwarePerformanceClaim:false};
window.__GPU_PHYSICS_QA={runCase,runOverflow,runRemoval,async runAnalytical(opts){if(running)throw Error('Probe already running');running=true;try{return show(await runAnalyticalGPU(gl,createGPUWorld,opts));}finally{running=false;}},async runLocalConsistency(name,opts){if(running)throw Error('Probe already running');running=true;try{return show(await runLocalGPU(gl,createGPUWorld,name,opts));}finally{running=false;}},capability,contract:GPU_CONTRACT,results,get last(){return last;},async runSmallSuite(){for(const n of['pair','stack','crowded','side','grid-edge'])await runCase(n,{steps:10});return results;}};
$('run').onclick=()=>runCase($('scene').value).catch(e=>show({error:String(e)}));$('long').onclick=()=>runCase($('scene').value,{steps:120}).catch(e=>show({error:String(e)}));$('remove').onclick=()=>runRemoval().catch(e=>show({error:String(e)}));$('overflow').onclick=()=>runOverflow().catch(e=>show({error:String(e)}));show({ready:true,capability,contract:GPU_CONTRACT,scope:'Only small GPU correctness gate initially; sleeping not implemented.'});document.documentElement.dataset.probeReady='true';
