import test from 'node:test';import assert from 'node:assert/strict';import {Game,PER_PIECE} from '../game.mjs';
function tick(g,{present=true}={}){g.step();if(present&&g.awaitingPresentation)assert(g.completePresentation(g.presentedToken+1));}
function settle(g,max=300){let n=0;while(g.phase==='settling'&&n++<max)tick(g);assert.notEqual(g.phase,'settling');return n}
test('whole block exists until actual contact then atomic 2304 identity cells',()=>{const g=new Game({seed:1});g.start();assert.equal(g.world.count,0);for(let k=0;k<10;k++)g.step();assert.equal(g.world.count,0);assert(g.active);g.drop();assert.equal(g.world.count,PER_PIECE);assert.equal(g.phase,'settling');assert.equal(g.active,null);assert.equal(g.world.pendingInbound,0);assert.equal(new Set(g.world.snapshot().map(p=>p.id)).size,2304);});
test('quiet physics cannot check or spawn until exact last output presentation',()=>{const g=new Game();g.start();g.drop();let token;for(let i=0;i<180;i++){g.step();token=g.presentationToken;if(!g.world.chunks.size)break;assert(g.completePresentation(token));}assert.equal(g.world.chunks.size,0);assert.equal(g.phase,'settling');assert(g.awaitingPresentation);const piece=g.pieceId;for(let k=0;k<5;k++)g.step();assert.equal(g.phase,'settling');assert.equal(g.pieceId,piece);assert(!g.completePresentation(token+1));assert(g.completePresentation(token));g.step();assert.equal(g.phase,'falling');assert.equal(g.pieceId,piece+1);assert.equal(g.world.pendingInbound,1);});
test('presentations reject missing, future, duplicate and non-head tokens',()=>{const g=new Game();g.start();g.drop();g.step();g.step();assert(!g.completePresentation(2));assert(!g.completePresentation(0));assert(g.completePresentation(1));assert(!g.completePresentation(1));assert(g.completePresentation(2));assert(!g.completePresentation(3));});
test('supported full-color clear waits flash then settles before new spawn',()=>{const g=new Game();g.state='playing';g.phase='settling';const a=Array.from({length:232},(_,i)=>({x:28+i,y:419,color:1})),b=Array.from({length:40},(_,i)=>({x:124+i,y:418,color:2}));assert(g.world.addMany(a).accepted);assert(g.world.addMany(b).accepted);g.added=272;settle(g);assert.equal(g.phase,'flash');assert.equal(g.pendingClear.flat().length,232);const initial=g.pieceId;for(let i=0;i<11;i++)g.step();assert.equal(g.world.count,272);g.step();assert.equal(g.phase,'settling');assert.equal(g.world.count,40);assert.equal(g.pieceId,initial);assert(g.world.chunks.size>0);settle(g);assert.equal(g.phase,'falling');assert.equal(g.pieceId,initial+1);assert(g.world.snapshot().every(p=>p.y===419));assert.equal(g.rawCleared,232);});
test('paused and settled phases reject piece movement; reset discards tokens',()=>{const g=new Game();g.start();g.pause();const x=g.active.x,t=g.gameTick;assert(!g.move(24));assert(!g.step());assert.equal(g.gameTick,t);g.resume();assert.equal(g.active.x,x);g.drop();assert(!g.rotate());assert(!g.softDrop());g.step();g.reset(1);assert.equal(g.presentationToken,0);assert(!g.completePresentation(1));assert.equal(g.world.count,0);});
test('capacity rejects whole admission without partial material',()=>{const g=new Game();g.world.maxParticles=2303;g.start();g.drop();assert.equal(g.state,'over');assert.equal(g.world.count,0);assert.equal(g.added,0);});
test('unobstructed rigid sweep cannot prematurely release',()=>{const g=new Game();g.start();assert.throws(()=>g.touchDown(),/before contact/);assert.equal(g.world.count,0);assert.equal(g.phase,'falling');});
