import test from 'node:test';import assert from 'node:assert/strict';
import {Game,RNG,SHAPES,rotateShape,WIDTH,HEIGHT,BLOCK} from '../dist/engine.js';
import {InputState} from '../dist/input.js';
test('PRNG remains unsigned and deterministic after many draws',()=>{let a=new RNG(42),b=new RNG(42);for(let i=0;i<200000;i++){assert.equal(a.next(),b.next());assert(a.state>=0&&a.state<=0xffffffff);}});
test('All pieces have four distinct blocks and rotation preserves shape',()=>{for(const shape of SHAPES){let s=shape;for(let i=0;i<4;i++)s=rotateShape(s);const normal=a=>a.map(x=>x.join(',')).sort();assert.deepEqual(normal(s),normal(shape));assert.equal(new Set(normal(s)).size,4);}});
test('Bounds cannot be crossed, horizontal movement does not tunnel through sand',()=>{let g=new Game({seed:6});g.start();g.move(-10000);assert.equal(Math.min(...g.active.shape.map(p=>g.active.x+p[0]*BLOCK)),0);assert(!g.canPlace(-1,0));g.move(10000);assert.equal(Math.max(...g.active.shape.map(p=>g.active.x+(p[0]+1)*BLOCK)),WIDTH);assert(!g.canPlace(0,HEIGHT));g.active={shape:[[0,0]],color:1,x:0,y:0};g.grid[10]=2;g.move(20);assert.equal(g.active.x,2);});
test('A locked tetromino creates exactly 256 grains; sand preserves particles',()=>{const g=new Game({seed:9});g.start();g.hardDrop();assert.equal(g.count(),256);for(let n=0;n<300;n++){g.tick++;g.sandStep();assert.equal(g.count(),256);}assert.equal(g.added,256);assert.equal(g.removed,0);});
test('Sand cannot enter any grain occupied by a rigid active piece',()=>{const g=new Game();g.state='playing';g.active={shape:[[0,0]],x:30,y:70,color:1};g.grid[69*WIDTH+34]=2;for(let n=0;n<100;n++){g.tick++;g.sandStep();for(let y=70;y<78;y++)for(let x=30;x<38;x++)assert.equal(g.grid[y*WIDTH+x],0);}assert.equal(g.count(),1);});
test('4-neighbor connectivity clears full region including branches',()=>{const g=new Game({width:8,height:8});for(let x=0;x<8;x++)g.grid[7*8+x]=1;g.grid[6*8+3]=1;g.grid[5*8+3]=1;assert.deepEqual(g.findConnections(),{count:10,regions:1});});
test('Diagonal-only contact does not clear',()=>{const g=new Game({width:8,height:8});for(let x=0;x<8;x++)g.grid[x*8+x]=1;assert.deepEqual(g.findConnections(),{count:0,regions:0});});
test('Different colors do not form a region; detached grains survive',()=>{const g=new Game({width:8,height:8});for(let x=0;x<8;x++)g.grid[56+x]=x<4?1:2;assert.equal(g.findConnections().count,0);for(let x=0;x<8;x++)g.grid[56+x]=1;g.grid[0]=2;g.state='playing';g.beginClear();g.finishClear();assert.equal(g.count(),1);assert.equal(g.grid[0],2);});
test('Multiple separate spanning regions clear together and chains multiply',()=>{const g=new Game({width:8,height:8});g.state='playing';for(let x=0;x<8;x++){g.grid[56+x]=1;g.grid[40+x]=2;}g.beginClear();assert.equal(g.clearRegions,2);assert.equal(g.clearCount,16);g.finishClear();assert.equal(g.score,216);assert.equal(g.chain,1);for(let x=0;x<8;x++)g.grid[56+x]=3;g.beginClear();g.finishClear();assert.equal(g.score,432);assert.equal(g.chain,2);assert.equal(g.maxChain,2);});
test('Paused game accepts no movement, rotation, drop or time',()=>{const g=new Game();g.start();g.pause();let old=JSON.stringify(g.snapshot()),active=JSON.stringify(g.active);for(let i=0;i<100;i++){g.step();g.move(4);g.rotate();g.hardDrop();}assert.equal(JSON.stringify(g.snapshot()),old);assert.equal(JSON.stringify(g.active),active);g.resume();g.step();assert.equal(g.tick,1);});
test('Blocked spawn ends game without overwriting sand',()=>{const g=new Game();g.grid.fill(1,0,WIDTH*32);let n=g.count();g.start();assert.equal(g.state,'over');assert.equal(g.active,null);assert.equal(g.count(),n);});
test('Fixed-step simulation is deterministic and conserves all created grains',()=>{const a=new Game({seed:1234}),b=new Game({seed:1234});a.start();b.start();for(let t=0;t<9000;t++){for(const g of[a,b]){if(t%53===0)g.move(t%2?20:-20);if(t%37===0)g.rotate();if(t%61===0)g.hardDrop();g.step({softDrop:t%9<3});if(t%101===0)assert.equal(g.count(),g.added-g.removed);}assert.deepEqual(a.grid,b.grid);assert.deepEqual(a.snapshot(),b.snapshot());}});
test('Reset fully clears state across 100 consecutive sessions',()=>{const g=new Game();for(let n=0;n<100;n++){g.reset(n);g.start();g.hardDrop();g.step();g.pause();g.reset(n+1);assert.equal(g.count(),0);assert.equal(g.score,0);assert.equal(g.state,'ready');assert.equal(g.clearCount,0);assert.equal(g.added,0);assert.equal(g.events.length,0);}});
test('Held-input timing, multiple pointers and cancellation are bounded',()=>{const input=new InputState();let total=0;assert(input.press('one','left'));assert(!input.press('one','left'));for(let i=0;i<16;i++)input.step(x=>total+=x);assert.equal(total,-12);input.press('two','down');assert(input.has('down'));input.release('one');for(let i=0;i<40;i++)input.step(x=>total+=x);assert.equal(total,-12);input.clear();assert.equal(input.held.size,0);assert(!input.has('down'));});

test('Discrete accessible soft-drop advances safely and respects pause',()=>{const g=new Game();g.start();const y=g.active.y;assert(g.nudgeDown());assert.equal(g.active.y,y+4);g.pause();assert(!g.nudgeDown());assert.equal(g.active.y,y+4);});

test('Duplicate movement sources do not accelerate and opposites cancel',()=>{let a=new InputState(),b=new InputState(),one=0,two=0;a.press('left','left');b.press('left','left');for(let n=0;n<60;n++){if(n===1)assert(!b.press('A','left'));a.step(v=>one+=v);b.step(v=>two+=v);}assert.equal(one,two);b.press('right','right');let total=0;for(let n=0;n<60;n++)b.step(v=>total+=v);assert.equal(total,0);b.release('left');assert(b.has('left'));b.release('A');for(let n=0;n<16;n++)b.step(v=>total+=v);assert.equal(total,12);});
