import test from 'node:test';import assert from 'node:assert/strict';
import {textureOffset,ACCESSIBLE_COLORS}from'../dist/palette.js';import{SessionMetrics}from'../dist/metrics.js';
test('Three accessible colors have distinct repeating non-color textures',()=>{let patterns=[];for(let c=1;c<=3;c++){let p=[];for(let y=0;y<12;y++)for(let x=0;x<12;x++)p.push(textureOffset(c,x,y));assert(new Set(p).size>=2);patterns.push(p.join(','));}assert.equal(new Set(patterns).size,3);assert.equal(ACCESSIBLE_COLORS.length,4);});
test('Full-session performance percentiles retain early frames beyond ring size',()=>{const m=new SessionMetrics(0);for(let i=0;i<10000;i++)m.record(i<1000?25:1,16,true,i*16);const s=m.snapshot(160000);assert.equal(s.frames,10000);assert(s.workP95>=25&&s.workP95<=25.05);assert.equal(s.playingFrames,10000);assert.equal(s.playingElapsedMs,160000);assert.equal(s.workMax,25);});
test('Performance record separates pauses, validates values and samples heap at 30s',()=>{const m=new SessionMetrics(0);for(let i=0;i<100;i++)m.record(i===0?NaN:1,16,i%2===0,i*1000,{usedJSHeapSize:i*100,totalJSHeapSize:10000});const s=m.snapshot(100000);assert.equal(s.playingFrames,50);assert.equal(s.heapSamples.length,4);assert.equal(s.heapSamples[1].elapsedMs,30000);assert(Number.isFinite(s.workMean));});

test('Full-session frame gaps retain early stalls and separate paused intervals',()=>{const m=new SessionMetrics();for(let i=0;i<10000;i++)m.record(1,i<1000?40:16,true,i*16);m.record(1,4000,false,170000);const s=m.snapshot(170000);assert.equal(s.playingGapsOver25ms,1000);assert.equal(s.playingGapsOver25msRatio,.1);assert(s.playingFrameGapP95>=40&&s.playingFrameGapP95<=40.5);assert.equal(s.playingFrameGapMax,40);assert.equal(s.frameGapMax,4000);});
test('Overflow percentiles explicitly return observed maxima',()=>{const m=new SessionMetrics();for(let i=0;i<100;i++)m.record(150,1500,true,i*1500);const s=m.snapshot(150000);assert.equal(s.workP95,150);assert.equal(s.frameGapP95,1500);assert.equal(s.workOverflowThresholdMs,100);assert.equal(s.gapOverflowThresholdMs,1000);});
test('An initial RAF timestamp before setup does not produce negative elapsed times',()=>{const m=new SessionMetrics(15);m.record(1,16,false,7,{usedJSHeapSize:10,totalJSHeapSize:100});assert.equal(m.snapshot(7).elapsedMs,0);assert.equal(m.snapshot(20).heapSamples[0].elapsedMs,0);});
