import test from'node:test';import assert from'node:assert/strict';import{Game,SHAPES,R,BLOCK,FLOOR,PER_PIECE}from'../game.mjs';import{GridWorld,SAND_CONTRACT as C,auditCircles,slotPosition}from'../grid-world.mjs';
const start=()=>{let g=new Game({seed:1});g.next={shape:SHAPES[0],color:1};g.start();return g};
const audit=w=>assert.ok(auditCircles(w.bodies()).passed);
test('old proximity witness stays a rigid airborne block with zero admission',()=>{let g=start();g.active={...g.active,x:120,y:200};g.world.add({row:111,col:51,color:4});assert.ok(g.canPlace(g.active));g.step();assert.ok(g.active);assert.equal(g.added,0);assert.equal(g.world.stats().live,1);assert.equal(g.events.some(e=>e.type==='land'),false)});
test('moving sand cannot enter the rigid silhouette; it remains awake and releases when obstacle moves away',()=>{
 let w=new GridWorld({seed:1}),b=w.add({row:80,col:65,color:2}),p=slotPosition(79,65);w.setRigidObstacle([{x0:p.x-4,y0:p.y-.1,x1:p.x+4,y1:p.y+5}]);assert.ok(b.y+R<p.y-.1);b.vy=180;b.motionCredit=10;let row=b.row;w.step();assert.equal(b.row,row);assert.equal(b.sleep,false);assert.ok(w.active.has(b.id));w.setRigidObstacle([]);w.step(30);assert.ok(b.row<row);audit(w);
});
test('free fall accelerates downwards without accumulating random horizontal drift, across four seeds',()=>{for(let seed=1;seed<=4;seed++){let w=new GridWorld({seed}),b=w.add({row:250,col:65,color:1}),x=b.x,y=b.y,first=0,later=0;for(let t=0;t<120;t++){let old=b.y;w.step();if(t<30)first+=b.y>old;else if(t>=90)later+=b.y>old;assert.ok(Math.abs(b.x-x)<=C.spacing*.5+1e-9);assert.ok(b.y>=y);assert.equal(w.stats().lastTick.rollMoves,0)}assert.ok(later>first);assert.ok(b.y-y>100);audit(w)}});
test('flat and double-slot support remain at rest until a lower vacancy opens',()=>{let w=new GridWorld(),b=w.add({row:0,col:60,color:1});w.step(60);assert.equal(b.col,60);assert.ok(b.sleep);let v=new GridWorld(),top=v.add({row:1,col:60,color:2});let floor=v.addMany([{row:0,col:60,color:1},{row:0,col:61,color:1}]);let x=top.x;v.step(120);assert.equal(top.row,1);assert.equal(top.x,x);assert.ok(top.sleep);v.remove([floor.addedIds[0]]);v.step();assert.equal(top.row,0);audit(v)});
for(let mode of['soft','hard'])test(`${mode} drop keeps sand absent in air, contacts floor and admits precisely 676`,()=>{let g=start();for(let i=0;i<10;i++){g.softDrop();assert.ok(g.active);assert.equal(g.added,0)}if(mode==='hard')g.drop();else{let n=0;while(g.active&&n++<100)g.softDrop()}assert.equal(g.added,PER_PIECE);assert.equal(g.world.stats().live,PER_PIECE);assert.equal(g.active,null);audit(g.world);});
test('irregular settled pile contact resolves a legal fractional pose; move/rotate and subsequent sand do not penetrate',()=>{let g=start();g.active={...g.active,x:120,y:200};const terrain=[];for(let row=0;row<12;row++)for(let col=55+Math.floor(row/3);col<=78-Math.floor(row/2);col++)terrain.push({row,col,color:2+(row%3)});g.world.addMany(terrain);g.added=terrain.length;g.world.step(180);audit(g.world);assert.ok(g.canPlace(g.active));g.rotate();g.move(2);g.drop();assert.equal(g.added,terrain.length+676);assert.equal(g.world.stats().live,g.added);audit(g.world);for(let i=0;i<90;i++){g.step();audit(g.world);if(g.active)assert.ok(g.canPlace(g.active));assert.equal(g.world.stats().live+g.rawCleared,g.added)}});
test('sleeping supported grains wake and descend after removal, preserving identity and count',()=>{let w=new GridWorld();let ids=w.addMany(Array.from({length:132},(_,col)=>({row:0,col,color:1}))).addedIds,top=w.add({row:1,col:60,color:2});w.step(30);assert.ok(top.sleep);w.remove([ids[60]]);assert.equal(top.sleep,false);let y=top.y;w.step(30);assert.ok(top.y>y);assert.equal(w.stats().live,132);audit(w)});
