import test from'node:test';import assert from'node:assert/strict';import{Game,SHAPES}from'../game.mjs';import{GridWorld,auditCircles,SAND_CONTRACT as C}from'../grid-world.mjs';function check(w){assert.ok(auditCircles(w.bodies()).passed);for(const b of w.bodies())if(b.sleep)assert.equal(w._down(b.row,b.col,false),null,'no directly unsupported sleeper');}
test('all seven isolated floor-contact shapes settle within the predeclared one second and then visit zero grains',()=>{for(const shape of SHAPES){let g=new Game({seed:1});g.next={shape,color:1};g.start();g.drop();for(let i=0;i<120&&g.world.stats().active;i++){g.world.step();assert.equal(g.world.stats().live,676);check(g.world)}assert.equal(g.world.stats().active,0);g.world.step(120);assert.equal(g.world.stats().lastTick.visits,0)}});
test('repeated explicit support removal preserves identities, wakes and settles without ageing out grains',()=>{let w=new GridWorld(),id=0;w.addMany(Array.from({length:132},(_,col)=>({id:id++,row:0,col,color:1})));w.addMany(Array.from({length:80},(_,i)=>({id:id++,row:1+Math.floor(i/40),col:46+i%40,color:2})));w.step(240);for(let k=0;k<12;k++){let bottom=w.bodies().filter(b=>b.row===0).sort((a,b)=>Math.abs(a.x-144)-Math.abs(b.x-144)).slice(0,4);let live=w.stats().live;w.remove(bottom.map(b=>b.id));assert.ok(w.stats().active>0);for(let t=0;t<240&&w.stats().active;t++)w.step();assert.equal(w.stats().live,live-bottom.length);assert.equal(w.stats().active,0);check(w)}w.step(120);assert.equal(w.stats().lastTick.visits,0)});
test('contact compaction is one bounded downward edge; unsupported free flight keeps gravity credit',()=>{let w=new GridWorld(),b=w.add({row:1,col:60,color:1});w.step();assert.equal(b.row,0);assert.equal(w.stats().lastTick.contactMoves,1);let v=new GridWorld(),air=v.add({row:100,col:60,color:2});v.step();assert.equal(air.row,100);assert.ok(air.motionCredit>0);assert.equal(v.stats().lastTick.contactMoves,0);assert.equal(C.gravity,900);assert.equal(C.fallSpeedCap,180);assert.equal(C.maxMovesPerParticlePerTick,1)});

test('two-slot contact pocket keeps one-edge budget, larger void and temporary rigid support remain credited',()=>{
 const pocket=new GridWorld(),b=pocket.add({row:2,col:60,color:1});pocket.step();assert.equal(b.row,1);assert.equal(pocket.stats().lastTick.contactMoves,1);pocket.step();assert.equal(b.row,0);check(pocket);const air=new GridWorld(),a=air.add({row:3,col:60,color:1});air.step();assert.equal(a.row,3);assert.equal(air.stats().lastTick.contactMoves,0);const rigid=new GridWorld(),r=rigid.add({row:20,col:60,color:1});rigid.setRigidObstacle([{x0:r.x-10,x1:r.x+10,y0:r.y+2,y1:r.y+5}]);rigid.step();assert.equal(r.row,20);assert.equal(r.sleep,false);rigid.setRigidObstacle([]);rigid.step(240);check(rigid);assert.equal(r.row,0);
});
test('full connection graph matches an independent distance-based oracle across colors, parity and support loss',()=>{
 const w=new GridWorld({seed:3});w.addMany(Array.from({length:330},(_,i)=>{const row=i<132?0:i<263?1:2,col=i<132?i:i<263?i-132:i-263;return{row,col,color:row<2?row+1:3+i%2}}));
 const signature=components=>components.map(c=>({color:c.color,ids:[...c.ids].sort((a,b)=>a-b),touchesLeft:c.touchesLeft,touchesRight:c.touchesRight,crosses:c.crosses})).sort((a,b)=>a.ids[0]-b.ids[0]);
 for(let round=0;round<5;round++){const bodies=w.bodies(),seen=new Set(),components=[];for(const start of bodies){if(seen.has(start.id))continue;const queue=[start],ids=[];seen.add(start.id);let left=false,right=false;for(let i=0;i<queue.length;i++){const b=queue[i];ids.push(b.id);left||=Math.abs(b.x-(C.left+C.radius))<1e-8;right||=Math.abs(b.x-(C.right-C.radius))<1e-8;for(const n of bodies)if(!seen.has(n.id)&&n.color===b.color&&Math.abs(Math.hypot(n.x-b.x,n.y-b.y)-C.spacing)<1e-7){seen.add(n.id);queue.push(n)}}components.push({color:start.color,ids,touchesLeft:left,touchesRight:right,crosses:left&&right})}const actual=w.connections();assert.deepEqual(signature(actual.components),signature(components));assert.deepEqual(signature(actual.spanningComponents),signature(components.filter(c=>c.crosses)));assert.ok(Object.isFrozen(actual.components[0].ids));const victims=bodies.filter(b=>b.row===0).slice(round*3,round*3+3);w.remove(victims.map(b=>b.id));w.step(20)}
});
