// Models WebGL call/state lifecycle only; does not execute shaders or paint.
export class FakeGL {
 constructor(){let e=1;for(const key of 'VERSION RENDERER HIGH_FLOAT RENDERBUFFER_DEPTH_SIZE VERTEX_SHADER FRAGMENT_SHADER COMPILE_STATUS LINK_STATUS RGBA32F RGBA FLOAT RGBA8UI RGBA_INTEGER UNSIGNED_BYTE R32UI RED_INTEGER UNSIGNED_INT TEXTURE_2D TEXTURE_MIN_FILTER TEXTURE_MAG_FILTER TEXTURE_WRAP_S TEXTURE_WRAP_T NEAREST CLAMP_TO_EDGE ARRAY_BUFFER RENDERBUFFER DEPTH_COMPONENT32F FRAMEBUFFER COLOR_ATTACHMENT0 DEPTH_ATTACHMENT FRAMEBUFFER_COMPLETE DYNAMIC_DRAW BLEND DITHER CULL_FACE SCISSOR_TEST DEPTH_TEST LESS COLOR DEPTH TRIANGLES SYNC_GPU_COMMANDS_COMPLETE ALREADY_SIGNALED CONDITION_SATISFIED WAIT_FAILED TIMEOUT_EXPIRED QUERY_RESULT_AVAILABLE QUERY_RESULT'.split(' '))this[key]=e++;this.TEXTURE0=1000;this.NO_ERROR=0;this.INVALID_OPERATION=1282;this.OUT_OF_MEMORY=1285;this.unit=0;this.textures=new Map();this.trace=[];this.livePrograms=new Set();this.serial=0;this.error=0;this.lost=false;this.signaled=false;this.feedback=0;this.doubleEnd=0;this.ext={TIME_ELAPSED_EXT:3000,GPU_DISJOINT_EXT:3001};}
 object(kind){return {kind,id:++this.serial};}
 createShader(kind){return {...this.object('Shader'),shaderKind:kind};} shaderSource(s,text){s.source=text;} compileShader(){} getShaderParameter(s){return !(this.failShadeCompile&&s.source.includes('vec3 matte('));} getShaderInfoLog(){return 'mock shade compilation rejected';} deleteShader(){}
 createProgram(){const p={...this.object('Program'),shaders:[],values:new Map()};this.livePrograms.add(p);return p;} attachShader(p,s){p.shaders.push(s);} linkProgram(p){p.source=p.shaders.map(s=>s.source).join('\n');} getProgramParameter(){return true;} deleteProgram(p){this.livePrograms.delete(p);} getProgramInfoLog(){return '';}
 getUniformLocation(p,name){return new RegExp('uniform[^;]*\\b'+name+'\\s*;').test(p.source)?{p,name}:null;} uniform1i(u,v){if(u)u.p.values.set(u.name,v);} uniform2i(u,...v){if(u)u.p.values.set(u.name,v);} useProgram(p){this.program=p;}
 getParameter(key){if(key===this.VERSION)return 'WebGL 2.0 mock';if(key===this.RENDERER)return 'Mock only, no shader execution';if(key===this.ext.GPU_DISJOINT_EXT)return !!this.disjoint;return 0;} getExtension(){return this.noTimer?null:this.ext;} getShaderPrecisionFormat(){return {precision:this.precision??23,rangeMin:127,rangeMax:127};} getRenderbufferParameter(){return this.depthBits??32;} getError(){const e=this.error;this.error=0;return e;} isContextLost(){return this.lost;}
 createTexture(){return this.object('Texture');} deleteTexture(){} activeTexture(unit){this.unit=unit-this.TEXTURE0;} bindTexture(_,t){this.textures.set(this.unit,t);} texParameteri(){} texImage2D(){} texSubImage2D(){if(this.injectUpload)this.error=this.injectUpload;}
 createVertexArray(){return this.object('VertexArray');} deleteVertexArray(){} bindVertexArray(){} createBuffer(){return this.object('Buffer');} deleteBuffer(){} bindBuffer(){} enableVertexAttribArray(){} vertexAttribIPointer(){} vertexAttribDivisor(){} bufferData(_,data){this.instances=data.slice();}
 createRenderbuffer(){return this.object('Renderbuffer');} deleteRenderbuffer(){} bindRenderbuffer(){} renderbufferStorage(){}
 createFramebuffer(){return this.object('Framebuffer');} deleteFramebuffer(){} bindFramebuffer(_,fbo){this.fbo=fbo;} framebufferTexture2D(_a,_b,_c,t){this.fbo.color=t;} framebufferRenderbuffer(_a,_b,_c,r){this.fbo.depth=r;} checkFramebufferStatus(){return this.FRAMEBUFFER_COMPLETE;}
 viewport(){} disable(){} enable(){} depthMask(){} depthFunc(value){this.depth=value;} clearBufferuiv(_a,_b,data){(this.clears??=[]).push({kind:'owner',framebuffer:this.fbo,value:[...data]});} clearBufferfv(_a,_b,data){(this.clears??=[]).push({kind:'depth',framebuffer:this.fbo,value:[...data]});}
 checkFeedback(){if(this.fbo){for(const match of this.program.source.matchAll(/uniform\s+(?:highp\s+)?(?:u?sampler2D)\s+(\w+)\s*;/g)){const unit=this.program.values.get(match[1]);if(this.textures.get(unit)===this.fbo.color){this.feedback++;this.error=this.INVALID_OPERATION;}}}}
 drawArraysInstanced(_a,_b,_c,count){this.checkFeedback();this.trace.push({pass:this.program.values.get('uSecond'),depth:this.depth,count,framebuffer:this.fbo});if(this.injectSites)this.error=this.injectSites;}
 drawArrays(){this.checkFeedback();this.trace.push({pass:'shade'});if(this.injectShade)this.error=this.injectShade;}
 createQuery(){return this.object('Query');} beginQuery(){this.queryActive=true;} endQuery(){if(!this.queryActive)this.doubleEnd++;this.queryActive=false;} deleteQuery(){} getQueryParameter(_q,key){return key===this.QUERY_RESULT_AVAILABLE?this.signaled:2e6;}
 fenceSync(){if(this.injectFence)this.error=this.injectFence;return this.nullFence?null:this.object('Sync');} deleteSync(){} clientWaitSync(){return this.signaled?this.CONDITION_SATISFIED:this.TIMEOUT_EXPIRED;} flush(){}
}
