import test from'node:test';import assert from'node:assert/strict';import{performance}from'node:perf_hooks';
import{Game,RNG,SHAPES,WIDTH,HEIGHT,BLOCK,AREA_SCALE}from'../../dist/preview/engine.js';import{makeComparison,tickComparison,comparisonState}from'../../dist/preview/fixtures.js';
function materialTotals(g){const a=new Uint32Array(3*256);for(let i=0;i<g.size;i++)if(g.grid[i])a[(g.grid[i]-1)*256+g.material[i]]++;return a;}
test('Fine grid and rigid body use fixed 3x dimensions and 9x physical mass',()=>{const g=new Game();assert.equal(g.size,288*432);assert.equal(BLOCK,24);g.start();g.hardDrop();assert.equal(g.count(),2304);assert.equal(g.count()/AREA_SCALE,256);});
test('Piece RNG is isolated from arbitrary physical random work',()=>{const a=new Game({seed:73}),b=new Game({seed:73});for(let i=0;i<100;i++){for(let k=0;k<i*17;k++)a.physicsRng.next();assert.deepEqual(a.randomPiece(),b.randomPiece());}});
test('Empty-ground landing spreads then sleeps, conserving every material shade',()=>{const g=new Game({seed:1});g.connectionEnabled=false;g.start();g.active={shape:SHAPES[0],color:1,x:120,y:384,materialSeed:123};g.hardDrop();g.spawnDelay=1e9;const material=materialTotals(g);for(let n=0;n<180;n++){g.step();assert.equal(g.count(),2304);}assert.deepEqual(materialTotals(g),material);assert.equal(g.activeChunkCount,0);const widths=[];for(let x=0;x<WIDTH;x++)if(g.surface[x]<HEIGHT)widths.push(x);assert(widths.at(-1)-widths[0]+1>=72);const stable=g.grid.slice();for(let n=0;n<180;n++)g.step();assert.deepEqual(g.grid,stable);});
test('Velocity paths cannot tunnel through a horizontal bed or active rigid body',()=>{const g=new Game();g.state='playing';g.active={shape:[[0,0]],color:1,x:100,y:200};g.grid.fill(2,350*WIDTH);const i=190*WIDTH+110;g.grid[i]=1;g.material[i]=99;g.vy[i]=112;g.vx[i]=40;g.added=(HEIGHT-350)*WIDTH+1;g.wakeAll();for(let n=0;n<60;n++){g.tick++;g.sandStep();for(let y=200;y<224;y++)for(let x=100;x<124;x++)assert.equal(g.grid[y*WIDTH+x],0);}assert.equal(g.count(),(HEIGHT-350)*WIDTH+1);for(let i=351*WIDTH;i<g.size;i++)assert.notEqual(g.grid[i],1);});
test('Eight-neighbor clear preserves the original area score scale',()=>{const g=new Game({width:9,height:9});g.state='playing';g.grid.fill(1);g.material.fill(23);g.added=81;g.rebuildSurface();g.beginClear();assert.equal(g.clearCount,81);g.finishClear();assert.equal(g.count(),0);assert.equal(g.score,109);assert.equal(g.cleared,9);assert.equal(g.rawCleared,81);});
test('All A/B fixtures use conserved normalized masses and deterministic same inputs',()=>{for(const name of['landing','slope','collapse']){const a=makeComparison(name),b=makeComparison(name);const initial=comparisonState(a);assert.equal(initial.baseline.normalizedGrains,initial.fine.normalizedGrains);for(let n=0;n<780;n++){tickComparison(a);tickComparison(b);}assert.deepEqual(a.fine.grid,b.fine.grid);assert.deepEqual(a.fine.material,b.fine.material);assert.equal(a.fine.count(),a.fine.added-a.fine.removed);assert.equal(a.baseline.count(),a.baseline.added-a.baseline.removed);assert(a.finished);}});
test('A moving grain cannot squeeze diagonally through two closed rigid faces',()=>{const g=new Game({width:12,height:12});g.state='playing';g.active=null;g.spawnDelay=1e9;const x=5,y=5,i=y*12+x;g.grid[i]=1;g.material[i]=63;g.vx[i]=32;g.vy[i]=32;g.energy[i]=12;g.added=1;g.rigid[i+1]=1;g.rigid[i+12]=1;g.rigid[i-1]=1;g.rigid[i+11]=1;g.rebuildSurface();g.activeChunks.fill(2);for(let n=0;n<12;n++){g.tick++;g.sandStep();assert.equal(g.grid[i],1);assert.equal(g.count(),1);}});
test('Removing a sleeping support layer propagates continuous dense free fall without comb gaps',()=>{const p=makeComparison('collapse');for(let t=1;t<=180;t++){tickComparison(p);if(t<132)continue;const g=p.fine;for(let x=96;x<=192;x+=6){let top=g.height,bottom=-1;for(let y=0;y<g.height;y++)if(g.grid[y*g.width+x]){top=Math.min(top,y);bottom=y;}for(let y=top;y<=bottom;y++)assert(g.grid[y*g.width+x],`Suspended internal gap at tick ${t}, ${x},${y}`);}assert.equal(g.count(),g.added-g.removed);}assert.equal(p.fine.activeChunkCount,0);});
test('Dephased row traversal removes long horizontal airborne combs in both flow scenes',()=>{for(const scene of['landing','slope']){const p=makeComparison(scene);let longest=0;for(let t=1;t<=300;t++){tickComparison(p);if(t<75)continue;const g=p.fine;for(let y=1;y<g.height-1;y++){let run=0;for(let x=0;x<g.width;x++){const i=y*g.width+x;if(g.grid[i]===1&&!g.grid[i-g.width]&&!g.grid[i+g.width]){run++;longest=Math.max(longest,run);}else run=0;}}}assert(longest<8,`${scene} formed a ${longest}-grain synchronized airborne row`);}});
test('Coprime row traversal visits every resting grain at partial-tile widths',()=>{for(const width of[5,12,17,24,25]){const g=new Game({width,height:24});g.grid.fill(1);g.material.fill(32);g.wakeAll();g.sandStep();for(let i=0;i<g.size;i++)assert.equal(g.movedAt[i],g.physicsTick);}});
