import { LocalSandWorld, SAND_CONTRACT, rowColumns, auditCircles } from './engine.mjs';
import { DeterministicFeeder, SCENARIO_CONTRACT as C, deleteBottomRegion, isEngineIdle, conserve, summarizeTimes } from './scenario.mjs';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import os from 'node:os';
const now=()=>performance.now();
export function runFeedCase(target,{seed=1,maxTicks=C.maxSimulationTicks,maxWallMs=C.maxWallMs,colorBatch=C.colorBatch,independentCascadeWindow=false,cascadeMaxTicks=2400}={}){
 const world=new LocalSandWorld({seed}),feeder=new DeterministicFeeder({target,seed,row:world.maxRows-1,colorBatch}),sceneId=`feed-${target}-seed${seed}${colorBatch===32?'':'-batch'+colorBatch}`,start=now(),samples=[],packets=[],audits=[];let removed=0,phase='feeding',stopReason=null,quiet=0,fullFeedTick=null,settledTick=null,deletion=null,cascadeIdleTick=null;
 const guard=()=>{if(independentCascadeWindow&&deletion&&phase==='cascade'){if(world.tick-deletion.tick>=cascadeMaxTicks){stopReason='cascade-window-limit';return false;}}else if(!(independentCascadeWindow&&phase==='idle-after-delete')&&world.tick>=maxTicks){stopReason='simulation-tick-limit';return false;}if(now()-start>=maxWallMs){stopReason='wall-time-limit';return false;}return true;};
 const packet=(stage,artificialFixture=false)=>{const snap=world.snapshot();const counters=conserve(world,feeder.added,removed);if(new Set(snap.particles.map(p=>p.id)).size!==snap.particles.length)throw Error('Snapshot duplicate IDs');packets.push({sceneId,stage,source:C.source,seed,tick:snap.tick,time:snap.time,modelKind:snap.modelKind,interpolation:snap.interpolation,artificialFixture,counters,feeder:feeder.report(),stats:snap.stats,particles:snap.particles});};
 const step=()=>{const wholeStart=now(),feedStart=now(),feed=phase==='feeding'?feeder.pump(world):{attempts:0,added:0,rejected:0},feedMs=now()-feedStart,before=world.stats(),stepStart=now();world.step(1);const stepMs=now()-stepStart,after=world.stats();conserve(world,feeder.added,removed);const row={tick:world.tick,phase,stepMs,feedMs,feedAndStepDriverMs:now()-wholeStart,feedAttempts:feed.attempts,feedAdded:feed.added,feedRejected:feed.rejected,pendingFeed:feeder.remaining,alive:after.live,activeBefore:before.active,activeAfter:after.active,queuedBefore:before.queued,queuedAfter:after.queued,sleepingAfter:after.sleeping,...after.lastTick};samples.push(row);return after;};
 let quarterCaptured=false;
 while(guard()){
  const stats=step();if(!quarterCaptured&&feeder.added>=Math.ceil(target/4)){packet('feed-quarter');quarterCaptured=true;}
  if(feeder.remaining===0&&fullFeedTick===null){fullFeedTick=world.tick;packet('fully-fed');phase='settling';}
  quiet=feeder.remaining===0&&isEngineIdle(stats)?quiet+1:0;
  if(quiet>=C.settleQuietTicks){settledTick=world.tick;packet('engine-idle-before-delete');break;}
 }
 let idleCountBefore=0,idleCountAfter=0;
 if(settledTick!==null&&!stopReason){
  phase='idle-before-delete';for(let i=0;i<C.idleSampleTicks&&guard();i++){const s=step();if(!isEngineIdle(s))throw Error('Claimed idle scene woke without an external edit');idleCountBefore++;}
  if(!stopReason){const t=now();deletion=deleteBottomRegion(world);deletion.wallMs=now()-t;removed+=deletion.removedIds.length;deletion.tick=world.tick;deletion.activeImmediately=world.stats().active;deletion.queuedImmediately=world.stats().queued;packet('immediately-after-bottom-delete');phase='cascade';quiet=0;let progressCaptured=false;
   while(guard()){const stats=step();const elapsed=world.tick-deletion.tick;if(!progressCaptured&&elapsed>=30){packet('cascade-after-30ticks');progressCaptured=true;}quiet=isEngineIdle(stats)?quiet+1:0;if((independentCascadeWindow?isEngineIdle(stats):(quiet>=C.settleQuietTicks&&elapsed>=30))){cascadeIdleTick=world.tick;packet('engine-idle-after-cascade');break;}}
   if(cascadeIdleTick!==null&&!stopReason){phase='idle-after-delete';for(let i=0;i<C.idleSampleTicks&&guard();i++){const s=step();if(!isEngineIdle(s))throw Error('Post-cascade idle scene woke unexpectedly');idleCountAfter++;}}
  }
 }
 if(stopReason)packet(`stopped-${stopReason}`);
 const auditStart=now();for(const p of packets.filter(p=>p.stage==='engine-idle-before-delete'||p.stage==='engine-idle-after-cascade'||p.stage.startsWith('stopped-'))){audits.push({stage:p.stage,...auditCircles(p.particles)});}const auditWallMs=now()-auditStart;
 const active=samples.slice(1).filter(s=>s.activeBefore>0||s.activeAfter>0),idle=samples.filter(s=>s.phase.startsWith('idle-'));
 const cascade=samples.filter(s=>s.phase==='cascade'),totals=world.stats().totals,conservation=conserve(world,feeder.added,removed);
 const finalStats=world.stats();
 const observedDownMoves=cascade.reduce((n,s)=>n+s.downMoves,0);let cumulativeDown=0,tick90ObservedDown=null;for(const s of cascade){cumulativeDown+=s.downMoves;if(tick90ObservedDown===null&&observedDownMoves>0&&cumulativeDown>=observedDownMoves*.9)tick90ObservedDown=s.tick-deletion.tick;}let belowRun=0,sustainedOnePercentTick=null;const threshold=Math.max(1,Math.ceil(finalStats.live*.01));for(const s of samples.filter(s=>deletion&&s.tick>deletion.tick)){belowRun=s.activeAfter<=threshold?belowRun+1:0;if(belowRun===60&&sustainedOnePercentTick===null)sustainedOnePercentTick=s.tick-deletion.tick-59;}

 const completed=feeder.remaining===0&&settledTick!==null&&cascadeIdleTick!==null&&idleCountBefore===C.idleSampleTicks&&idleCountAfter===C.idleSampleTicks&&!stopReason;
 const report={sceneId,source:C.source,target,seed,modelKind:SAND_CONTRACT.modelKind,interpolation:'snap-only',continuousCirclePhysicsClaim:false,bounds:{left:28,right:260,floor:420},limits:{maxTicks,maxWallMs,independentCascadeWindow,cascadeMaxTicks:independentCascadeWindow?cascadeMaxTicks:null,maxFeedAttemptsPerTick:feeder.ports.length,maxMovesPerParticlePerTick:1},completed,stopReason,feedSucceeded:feeder.remaining===0,settledBeforeDeletion:settledTick!==null,cascadeCompleted:cascadeIdleTick!==null,finalStats,observedCascadeTicks:deletion?(cascadeIdleTick??world.tick)-deletion.tick:0,postDeletionTotalObservedTicks:deletion?world.tick-deletion.tick:0,simulatedTicks:world.tick,simulatedSeconds:world.time,simulationAndAuditWallMs:now()-start,auditWallMs,fullFeedTick,settledTick,cascadeIdleTick,feeder:feeder.report(),conservation,firstStep:samples[0]??null,sustainedActiveStep:summarizeTimes(active.map(s=>s.stepMs)),sustainedActiveFeedAndStep:summarizeTimes(active.map(s=>s.feedAndStepDriverMs)),idleStep:summarizeTimes(idle.map(s=>s.stepMs)),idleCounts:{before:idleCountBefore,after:idleCountAfter},feeding:summarizeTimes(samples.filter(s=>s.feedAttempts).map(s=>s.feedMs)),maxActive:samples.reduce((m,s)=>Math.max(m,s.activeBefore,s.activeAfter),0),maxQueued:samples.reduce((m,s)=>Math.max(m,s.queuedBefore,s.queuedAfter,s.queuePeak),0),totalVisits:totals.visits,totalMoves:totals.moves,totalDownMoves:totals.downMoves,totalRollMoves:totals.rollMoves,totalNeighborVisits:totals.neighborVisits,perTickVisitBoundPassed:samples.every(s=>s.visits<=s.alive),deletion:deletion?{...deletion,removedIds:undefined,removedCount:deletion.removedIds.length,cascadeMoves:cascade.reduce((n,s)=>n+s.moves,0),cascadeDownMoves:cascade.reduce((n,s)=>n+s.downMoves,0),cascadeRollMoves:cascade.reduce((n,s)=>n+s.rollMoves,0),firstResponseTick:cascade.find(s=>s.moves>0)?.tick-deletion.tick||null,firstDownTick:cascade.find(s=>s.downMoves>0)?.tick-deletion.tick||null,tick90PercentOfObservedDownMoves:tick90ObservedDown,observedDownMoveDenominator:observedDownMoves,denominatorIsFinalOnlyIfCascadeCompleted:cascadeIdleTick!==null,sustainedActiveAtMostOnePercentTick:sustainedOnePercentTick,onePercentActiveThreshold:threshold,peakActive:cascade.reduce((m,s)=>Math.max(m,s.activeBefore,s.activeAfter),0),lastActive:finalStats.active,lastQueued:finalStats.queued}:null,audits,snapshots:packets.map(p=>({stage:p.stage,tick:p.tick,alive:p.particles.length})),timingScope:'Node CPU step timings; feed/driver, snapshots and audits disclosed separately. No browser/render FPS claim.'};
 return{report,samples,packets};
}
export function runArtificialBridge(){const world=new LocalSandWorld({seed:1}),particles=Array.from({length:rowColumns(0)},(_,col)=>({id:`bridge-${col}`,color:1,row:0,col})),added=world.addMany(particles);if(!added.accepted)throw Error('Artificial bridge fixture rejected');world.step();const before=world.snapshot(),start=now(),connected=world.connections(),connectionsMs=now()-start;const ids=connected.spanningComponents.flatMap(c=>c.ids),removed=world.remove(ids),after=world.snapshot();const pack=(stage,snap)=>({sceneId:'artificial-samecolor-wall-bridge',stage,source:'Artificial fixture: a full bottom row of one color, deliberately touching both walls; not naturally fed',artificialFixture:true,seed:1,tick:snap.tick,time:snap.time,modelKind:snap.modelKind,interpolation:snap.interpolation,counters:{added:particles.length,alive:snap.particles.length,removed:particles.length-snap.particles.length},stats:snap.stats,particles:snap.particles});return{report:{artificialFixture:true,source:'Full same-color bottom row explicitly placed for connectivity test',added:particles.length,spanningComponents:connected.spanningComponents.map(c=>({color:c.color,count:c.ids.length,touchesLeft:c.touchesLeft,touchesRight:c.touchesRight})),removed:removed.removedIds.length,remaining:after.particles.length,connectionsMs,passed:connected.spanningComponents.length===1&&removed.removedIds.length===particles.length&&after.particles.length===0,audit:auditCircles(before.particles)},packets:[pack('before-connected-clear',before),pack('after-connected-clear',after)]};}
export async function runBoundedBench({targets=[4056,12000],output=dirname(fileURLToPath(import.meta.url)),colorBatch=32,independentCascadeWindow=false}={}){
 const enginePath=new URL('./engine.mjs',import.meta.url),beforeText=await readFile(enginePath),engineSHA256=createHash('sha256').update(beforeText).digest('hex');await mkdir(resolve(output,'evidence'),{recursive:true});await mkdir(resolve(output,'snapshots'),{recursive:true});const reports=[];
 for(const target of targets){const result=runFeedCase(target,{colorBatch,independentCascadeWindow});reports.push(result.report);await writeFile(resolve(output,'evidence',`feed-${target}-ticks.json`),JSON.stringify(result.samples)+'\n');for(const packet of result.packets)await writeFile(resolve(output,'snapshots',`${packet.sceneId}-${String(packet.tick).padStart(4,'0')}-${packet.stage}.json`),JSON.stringify(packet)+'\n');console.log(JSON.stringify({target,completed:result.report.completed,stopReason:result.report.stopReason,added:result.report.feeder.added,remaining:result.report.feeder.remaining,removed:result.report.conservation.removed,ticks:result.report.simulatedTicks,activeP95Ms:result.report.sustainedActiveStep.p95Ms,activeP99Ms:result.report.sustainedActiveStep.p99Ms,idleP95Ms:result.report.idleStep.p95Ms,maxActive:result.report.maxActive,wallMs:result.report.simulationAndAuditWallMs}));}
 const bridge=runArtificialBridge();for(const packet of bridge.packets)await writeFile(resolve(output,'snapshots',`${packet.sceneId}-${packet.stage}.json`),JSON.stringify(packet)+'\n');const afterSHA256=createHash('sha256').update(await readFile(enginePath)).digest('hex');if(engineSHA256!==afterSHA256)throw Error('Engine source changed during benchmark; results cannot be assigned to one source');
 const report={candidate:'Independent discrete local slot-rule sand game prototype',engineSHA256,sourceModel:SAND_CONTRACT,scenario:C,platform:{node:process.version,platform:process.platform,arch:process.arch,cpu:os.cpus()[0]?.model},hardwareGameFPSClaim:false,runOptions:{colorBatch,independentCascadeWindow},reports,artificialBridge:bridge.report,allRequestedScenesCompleted:reports.every(r=>r.completed),allConservationPassed:reports.every(r=>r.conservation.passed),allCapturedGeometryAuditsPassed:reports.every(r=>r.audits.every(a=>a.passed)),allVisitBudgetsPassed:reports.every(r=>r.perTickVisitBoundPassed)};await writeFile(resolve(output,'evidence','benchmark-report.json'),JSON.stringify(report,null,2)+'\n');return report;
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){const selected=process.argv.find(v=>v.startsWith('--target=')),output=process.argv.find(v=>v.startsWith('--out=')),batch=process.argv.find(v=>v.startsWith('--color-batch='));await runBoundedBench({targets:selected?[Number(selected.split('=')[1])]:[4056,12000],output:output?resolve(output.slice(6)):dirname(fileURLToPath(import.meta.url)),colorBatch:batch?Number(batch.split('=')[1]):32,independentCascadeWindow:process.argv.includes('--equal-cascade-window')});}
