import { LocalSandWorld, SAND_CONTRACT, rowColumns } from './engine.mjs';
import { DeterministicFeeder, deleteBottomRegion, conserve, summarizeTimes } from './scenario.mjs';
const $=id=>document.getElementById(id),canvas=$('board'),ctx=canvas.getContext('2d'),palette=['','#eac370','#4fc0b3','#d378a3','#789fef'];
const DT=1/120,MAX_STEPS_PER_FRAME=12,FRAME_COMPUTE_SOFT_MS=6;
let world,feeders=[],added=0,removed=0,reservedIds=0,paused=false,accumulator=0,lastTimestamp=null,lastRevision=-1,stepTimes=[],lastDrawMs=0,lastFrameSteps=0,lastUi=0,sceneLabel='',artificial=false,manualSteps=0,feedAttempted=0,feedRejected=0,feedRefusalKinds=new Set();
function message(text){$('event').textContent=text;}
function pending(){return feeders.reduce((n,f)=>n+f.remaining,0);}
function queue(count,{color=null,colorBatch=64,seed=1}={}){const f=new DeterministicFeeder({target:count,seed,row:world.maxRows-1,idStart:reservedIds,colorBatch,fixedColor:color});reservedIds+=count;feeders.push(f);return{queued:count,color,colorBatch,pending:pending()};}
function startScene(target=256,{seed=1,colorBatch=target===256?64:676,paused:pause=false}={}){if(![256,4056,12000].includes(target))throw Error('Manual scene target must be 256, 4056 or 12000');world=new LocalSandWorld({seed});feeders=[];added=removed=reservedIds=0;paused=pause;accumulator=0;lastTimestamp=null;lastRevision=-1;stepTimes=[];manualSteps=0;feedAttempted=feedRejected=0;feedRefusalKinds=new Set();artificial=false;sceneLabel=`新规则确定投料场景：空盘→${target}，seed ${seed}，每 ${colorBatch} 粒同色切换；未导入旧状态`;queue(target,{seed,colorBatch});$('scene').textContent=sceneLabel;$('pause').textContent=paused?'继续':'暂停';message(`重开 ${target} 粒目标。待投料 ${target}；没有提前生成或隐藏粒子。`);return telemetry();}
function oneTick(){const f=feeders[0];if(f){const result=f.pump(world);added+=result.added;feedAttempted+=result.attempts;feedRejected+=result.rejected;for(const reason of Object.keys(f.rejections))feedRefusalKinds.add(reason);if(f.remaining===0)feeders.shift();}const start=performance.now();world.step(1);stepTimes.push(performance.now()-start);if(stepTimes.length>600)stepTimes.shift();conserve(world,added,removed);}
function deleteBottom(){const r=deleteBottomRegion(world);removed+=r.removedIds.length;conserve(world,added,removed);message(`大删底：真实移除 ${r.removedIds.length} 粒；唤醒后 active=${world.stats().active}、queued=${world.stats().queued}。`);return{removed:r.removedIds.length,...telemetry()};}
function clearConnected(){const c=world.connections(),ids=c.spanningComponents.flatMap(p=>p.ids),r=world.remove(ids);if(r.rejected)throw Error('Connected clear rejected');removed+=r.removedIds.length;conserve(world,added,removed);message(`按槽邻接判定 ${c.spanningComponents.length} 个同色跨左右墙组件，真实移除 ${r.removedIds.length} 粒。`);return{components:c.spanningComponents.map(p=>({color:p.color,count:p.ids.length,touchesLeft:p.touchesLeft,touchesRight:p.touchesRight})),removed:r.removedIds.length};}
function artificialBridge(){world=new LocalSandWorld({seed:1});feeders=[];added=removed=reservedIds=0;paused=true;accumulator=0;lastTimestamp=null;lastRevision=-1;stepTimes=[];manualSteps=0;feedAttempted=feedRejected=0;feedRefusalKinds=new Set();artificial=true;const specs=Array.from({length:rowColumns(0)},(_,col)=>({id:col,color:1,row:0,col})),r=world.addMany(specs);if(!r.accepted)throw Error('Artificial fixture rejected');added=reservedIds=r.addedIds.length;world.step(1);sceneLabel='人工 fixture：底行 132 粒同色，专门验证跨左右墙连接；不是自然投料堆。';$('scene').textContent=sceneLabel;$('pause').textContent='继续';message('人工 fixture 已暂停载入，可点击“消除跨左右墙同色”验证 132 粒清除。');return telemetry();}
function telemetry(){const s=world.stats();return{modelKind:SAND_CONTRACT.modelKind,interpolation:'snap-only',artificialFixture:artificial,tick:world.tick,simulationSeconds:world.time,live:s.live,active:s.active,sleeping:s.sleeping,queued:s.queued,pendingFeed:pending(),feedAttempted,feedRejected,feedRefusalKinds:[...feedRefusalKinds],added,removed,conservation:added===s.live+removed,paused,accumulatorSeconds:accumulator,backlogSteps:Math.floor(accumulator/DT),overloaded:accumulator>=.25,maxStepsPerFrame:MAX_STEPS_PER_FRAME,frameComputeSoftMs:FRAME_COMPUTE_SOFT_MS,lastFrameSteps,manualSteps,lastDrawMs,recentStepTimes:summarizeTimes(stepTimes),lastTick:s.lastTick,source:sceneLabel};}
function draw(){const s=world.stats();if(s.revision===lastRevision)return;lastRevision=s.revision;const start=performance.now(),particles=world.snapshot().particles;ctx.setTransform(canvas.width/288,0,0,canvas.height/432,0,0);ctx.fillStyle='#0b141b';ctx.fillRect(0,0,288,432);ctx.fillStyle='#4a626a';ctx.fillRect(24,0,4,424);ctx.fillRect(260,0,4,424);ctx.fillRect(24,420,240,4);for(const p of particles){if(!p.alive)continue;ctx.beginPath();for(let i=0;i<8;i++){const a=Math.PI/8+i*Math.PI/4,x=p.x+Math.cos(a)*.87,y=p.y+Math.sin(a)*.87;if(i)ctx.lineTo(x,y);else ctx.moveTo(x,y);}ctx.closePath();ctx.fillStyle=palette[p.color];ctx.fill();}lastDrawMs=performance.now()-start;}
function refresh(){const t=telemetry();$('status').textContent=`tick ${t.tick} · simulation ${t.simulationSeconds.toFixed(3)} s\nalive ${t.live} · active ${t.active} · sleep ${t.sleeping}\nengine queue ${t.queued} · feed pending ${t.pendingFeed}\nfeed attempts ${t.feedAttempted} · rejected ${t.feedRejected} (${t.feedRefusalKinds.join(',')||'none'})\nadded ${t.added} = alive ${t.live} + removed ${t.removed}\nconservation ${t.conservation?'PASS':'FAIL'}\n最近 step p95 ${t.recentStepTimes.p95Ms?.toFixed(3)??'—'} ms / p99 ${t.recentStepTimes.p99Ms?.toFixed(3)??'—'} ms\nlast actual draw ${t.lastDrawMs.toFixed(2)} ms · no interpolation\nlast tick: visits ${t.lastTick.visits}, moves ${t.lastTick.moves}, queue peak ${t.lastTick.queuePeak}`;$('lag').textContent=t.overloaded?`计算积压 ${t.backlogSteps} 个固定步（${t.accumulatorSeconds.toFixed(3)} 秒）。积压完整保留，未截断 dt；可暂停投料或等候消化。`:`固定 120Hz；待执行 ${t.backlogSteps} 步（${t.accumulatorSeconds.toFixed(4)} 秒）。每帧最多12步/6ms软预算；无时间丢弃。`;$('lag').style.borderColor=t.overloaded?'#ed8569':'#5bb7ab';}
function frame(timestamp){if(lastTimestamp===null)lastTimestamp=timestamp;const elapsed=(timestamp-lastTimestamp)/1000;lastTimestamp=timestamp;if(!paused)accumulator+=elapsed;const start=performance.now();lastFrameSteps=0;while(!paused&&accumulator>=DT&&lastFrameSteps<MAX_STEPS_PER_FRAME){if(lastFrameSteps>0&&performance.now()-start>=FRAME_COMPUTE_SOFT_MS)break;oneTick();accumulator-=DT;lastFrameSteps++;}draw();if(timestamp-lastUi>200){lastUi=timestamp;refresh();}requestAnimationFrame(frame);}
function setPaused(value){const now=performance.now();if(!paused&&lastTimestamp!==null)accumulator+=(now-lastTimestamp)/1000;paused=!!value;lastTimestamp=now;$('pause').textContent=paused?'继续':'暂停';refresh();return telemetry();}
$('pause').onclick=()=>setPaused(!paused);$('reset').onclick=()=>startScene(256);$('large4056').onclick=()=>startScene(4056);$('large12000').onclick=()=>startScene(12000);$('bottom').onclick=deleteBottom;$('clearConnected').onclick=clearConnected;$('fixture').onclick=artificialBridge;for(let color=1;color<=4;color++)$('c'+color).onclick=()=>message(JSON.stringify(queue(132,{color})));
window.__LOCAL_SAND_QA={startScene,queue,deleteBottom,clearConnected,artificialBridge,pause:setPaused,telemetry,snapshot:()=>world.snapshot(),advanceTicks(n=1){if(!paused)throw Error('Pause before explicit QA ticks');if(!Number.isInteger(n)||n<1||n>240)throw Error('QA tick burst must be 1..240');for(let i=0;i<n;i++)oneTick();manualSteps+=n;draw();refresh();return telemetry();}};
startScene(256);draw();refresh();document.documentElement.dataset.probeReady='true';requestAnimationFrame(frame);
