import { readFile,readdir,writeFile } from 'node:fs/promises';
import { resolve,dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
const quantiles=values=>{const a=[...values].sort((x,y)=>x-y),at=q=>a[Math.max(0,Math.ceil(a.length*q)-1)]??null;return{n:a.length,min:a[0]??null,p50:at(.5),p95:at(.95),p99:at(.99),max:a.at(-1)??null};};
const bins=values=>Object.fromEntries([[0,0],[1,10],[11,100],[101,1000],[1001,5000],[5001,Infinity]].map(([a,b])=>[`${a}..${b===Infinity?'inf':b}`,values.filter(v=>v>=a&&v<=b).length]));
const idCompare=(a,b)=>typeof a.id==='number'&&typeof b.id==='number'?a.id-b.id:String(a.id).localeCompare(String(b.id));
function state(packet,removedIds){return{version:'observable-engine-endpoint-state-v1',seed:packet.seed,tick:packet.tick,modelKind:packet.modelKind,interpolation:packet.interpolation,particles:[...packet.particles].sort(idCompare).map(p=>({id:p.id,color:p.color,row:p.row,col:p.col,x:p.x,y:p.y,alive:p.alive,sleep:p.sleep,vy:p.vy,motionCredit:p.motionCredit,mustDescendAfterRoll:p.mustDescendAfterRoll,lastMovedTick:p.lastMovedTick})),removedIds:[...removedIds].sort((a,b)=>typeof a==='number'&&typeof b==='number'?a-b:String(a).localeCompare(String(b)))};}
function lateral(particles){const n=particles.length,center=144,left=particles.filter(p=>p.x<center-1e-9).length,right=particles.filter(p=>p.x>center+1e-9).length,meanX=n?particles.reduce((s,p)=>s+p.x,0)/n:null;return{alive:n,meanX,offsetFromWorldCenter:meanX===null?null:meanX-center,leftCount:left,rightCount:right,centerCount:n-left-right,rightMinusLeftFraction:n?(right-left)/n:null,scope:'Actual endpoint distribution; not a proof that every input is unbiased'};}
export async function summarizeRun(directory){const report=JSON.parse(await readFile(resolve(directory,'evidence/benchmark-report.json'),'utf8')),files=await readdir(resolve(directory,'snapshots')),scenes=[];
 for(const r of report.reports){const prefix=r.sceneId+'-',matching=files.filter(f=>f.startsWith(prefix)&&f.endsWith('.json'));const packets=await Promise.all(matching.map(async f=>({file:f,packet:JSON.parse(await readFile(resolve(directory,'snapshots',f),'utf8'))})));const before=packets.find(x=>x.packet.stage==='engine-idle-before-delete'),end=packets.find(x=>x.packet.stage==='engine-idle-after-cascade')??packets.filter(x=>x.packet.stage.startsWith('stopped-')).at(-1)??packets.sort((a,b)=>a.packet.tick-b.packet.tick).at(-1);const ids=new Set(end.packet.particles.map(p=>p.id)),removedIds=before?before.packet.particles.filter(p=>!ids.has(p.id)).map(p=>p.id):[];const canonical=state(end.packet,removedIds),json=JSON.stringify(canonical),hash=createHash('sha256').update(json).digest('hex'),ticks=JSON.parse(await readFile(resolve(directory,'evidence',`feed-${r.target}-ticks.json`),'utf8'));
  scenes.push({sceneId:r.sceneId,engineSHA256:report.engineSHA256,stateHashSHA256:hash,stateStage:end.packet.stage,stateSnapshot:end.file,stateTick:end.packet.tick,canonicalStateFields:'Stable sorted live id/color/slot/xy/alive/sleep/vy/credit/roll-latch/lastMovedTick, actual removed IDs, tick, seed and model',completed:r.completed,conservation:r.conservation,activity:{active:quantiles(ticks.map(t=>t.activeAfter)),queued:quantiles(ticks.map(t=>t.queuedAfter)),visits:quantiles(ticks.map(t=>t.visits)),activeBins:bins(ticks.map(t=>t.activeAfter)),queueBins:bins(ticks.map(t=>t.queuedAfter)),maxMovesPerParticle:Math.max(...ticks.map(t=>t.maxMovesPerParticle))},offlineClock:{fixedDt:1/120,simulationSeconds:r.simulatedSeconds,measuredWallSeconds:r.simulationAndAuditWallMs/1000,simulatedSecondsPerWallSecond:r.simulatedSeconds/(r.simulationAndAuditWallMs/1000),scope:'Accelerated Node batch throughput, not browser wall-clock synchronization or rendered FPS'},lateralBeforeDeletion:before?lateral(before.packet.particles):null,lateralFinal:lateral(end.packet.particles),eventWindow:r.deletion?{maxTicks:r.limits.cascadeMaxTicks,observedTicks:r.observedCascadeTicks,firstResponseTicks:r.deletion.firstResponseTick,tick90PercentOfObservedDownMoves:r.deletion.tick90PercentOfObservedDownMoves,observedMovementIsFinal:r.deletion.denominatorIsFinalOnlyIfCascadeCompleted,sustainedAtMostOnePercentActiveTick:r.deletion.sustainedActiveAtMostOnePercentTick,lastActive:r.finalStats.active,lastQueued:r.finalStats.queued}:null});
 }
 const summary={sourceDirectory:directory,hashScope:'Deterministic observable state at the named actual snapshot; excludes wall timings. No snapshot restore is used.',engineSHA256:report.engineSHA256,scenes};await writeFile(resolve(directory,'evidence/reproducibility-summary.json'),JSON.stringify(summary,null,2)+'\n');return summary;
}
export async function compareSummaries(a,b){const first=JSON.parse(await readFile(a,'utf8')),second=JSON.parse(await readFile(b,'utf8'));const rows=first.scenes.map(x=>{const y=second.scenes.find(s=>s.sceneId===x.sceneId);return{sceneId:x.sceneId,present:!!y,sameEngine:x.engineSHA256===y?.engineSHA256,sameState:x.stateHashSHA256===y?.stateHashSHA256,sameActivity:JSON.stringify(x.activity)===JSON.stringify(y?.activity),sameEventWindow:JSON.stringify(x.eventWindow)===JSON.stringify(y?.eventWindow),timingComparedForEquality:false};});return{passed:rows.every(r=>r.present&&r.sameEngine&&r.sameState&&r.sameActivity&&r.sameEventWindow),rows};}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){if(process.argv[2]==='--compare')console.log(JSON.stringify(await compareSummaries(process.argv[3],process.argv[4]),null,2));else{const r=await summarizeRun(resolve(process.argv[2]??dirname(fileURLToPath(import.meta.url))));console.log(JSON.stringify(r,null,2));}}
