import { SAND_CONTRACT, rowColumns } from './engine.mjs';
export const SCENARIO_CONTRACT=Object.freeze({source:'New-rule deterministic feed from an empty board; not an old continuous-state replay',colorBatch:32,maxSimulationTicks:2400,maxWallMs:15000,idleSampleTicks:120,settleQuietTicks:16,deleteBottomRows:23,deleteSideMargin:32});
export function seededPorts(seed,row){let state=seed>>>0;const random=()=>((state=(Math.imul(state,1664525)+1013904223)>>>0)/2**32);const ports=Array.from({length:rowColumns(row)},(_,i)=>i);for(let i=ports.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[ports[i],ports[j]]=[ports[j],ports[i]];}return ports;}
export class DeterministicFeeder{
 constructor({target,seed=1,row=275,idStart=0,colorBatch=SCENARIO_CONTRACT.colorBatch,fixedColor=null}){if(!Number.isSafeInteger(target)||target<0)throw Error('Invalid target');if(!Number.isSafeInteger(colorBatch)||colorBatch<1)throw Error('Invalid colorBatch');if(fixedColor!==null&&![1,2,3,4].includes(fixedColor))throw Error('Invalid fixedColor');this.target=target;this.seed=seed;this.row=row;this.ports=seededPorts(seed,row);this.cursor=0;this.idStart=idStart;this.colorBatch=colorBatch;this.fixedColor=fixedColor;this.added=0;this.attempted=0;this.rejected=0;this.rejections={};this.last={attempts:0,added:0,rejected:0};}
 get remaining(){return this.target-this.added;}
 pump(world){const last={attempts:0,added:0,rejected:0};for(let i=0;i<this.ports.length&&this.remaining>0;i++){const col=this.ports[this.cursor++%this.ports.length],id=this.idStart+this.added,color=this.fixedColor??(1+Math.floor(this.added/this.colorBatch)%4);const result=world.add({id,color,row:this.row,col});this.attempted++;last.attempts++;if(result.accepted&&result.addedIds?.length===1&&result.addedIds[0]===id){this.added++;last.added++;}else{if(result.addedIds?.length)throw Error('Unexpected partial spawn result');this.rejected++;last.rejected++;const reason=result.reason??'unspecified';this.rejections[reason]=(this.rejections[reason]??0)+1;}}this.last=last;return last;}
 report(){return{target:this.target,added:this.added,remaining:this.remaining,attempted:this.attempted,rejected:this.rejected,rejections:{...this.rejections},seed:this.seed,row:this.row,portCount:this.ports.length,portOrder:this.ports.slice(),maxAttemptsPerTick:this.ports.length,colorBatch:this.colorBatch,fixedColor:this.fixedColor};}
}
export function deleteBottomRegion(world){const snap=world.snapshot(),ids=snap.particles.filter(p=>p.alive!==false&&p.row<SCENARIO_CONTRACT.deleteBottomRows&&p.x>=SAND_CONTRACT.left+SCENARIO_CONTRACT.deleteSideMargin&&p.x<=SAND_CONTRACT.right-SCENARIO_CONTRACT.deleteSideMargin).map(p=>p.id);const result=world.remove(ids);if(result.rejected||result.removedIds.length!==ids.length)throw Error('Bottom deletion failed atomically');return{removedIds:result.removedIds,region:{maxExclusiveRow:SCENARIO_CONTRACT.deleteBottomRows,left:SAND_CONTRACT.left+SCENARIO_CONTRACT.deleteSideMargin,right:SAND_CONTRACT.right-SCENARIO_CONTRACT.deleteSideMargin}};}
export function isEngineIdle(stats){return stats.active===0&&stats.queued===0;}
export function conserve(world,added,removed){const stats=world.stats();if(added!==stats.live+removed)throw Error(`Particle conservation failed: ${added} != ${stats.live} + ${removed}`);return{added,alive:stats.live,removed,passed:true};}
export function summarizeTimes(values){if(!values.length)return{count:0,meanMs:null,p95Ms:null,p99Ms:null,maxMs:null,stepsPerSecond:null,over120HzBudget:0};const sorted=[...values].sort((a,b)=>a-b),sum=values.reduce((a,b)=>a+b,0),at=q=>sorted[Math.max(0,Math.ceil(sorted.length*q)-1)];return{count:values.length,totalMs:sum,meanMs:sum/values.length,p50Ms:at(.5),p95Ms:at(.95),p99Ms:at(.99),maxMs:sorted.at(-1),stepsPerSecond:sum>0?1000*values.length/sum:null,over120HzBudget:values.filter(t=>t>SAND_CONTRACT.dt*1000).length,budgetMs:SAND_CONTRACT.dt*1000};}
