import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {CAWorld as Before} from '../evidence/baseline0411/ca-adapter.mjs';
import {CAWorld as After} from '../candidate/ca-adapter.mjs';
import {Game as OldGame} from '../evidence/baseline0411/game.mjs';
import {Game as NewGame} from '../candidate/game.mjs';
import {LEFT,FLOOR,FIELD_WIDTH} from '../candidate/board-geometry.mjs';
const state=w=>({cache:[...w.cache],changed:[...w.changedBodies],removed:[...w.removedBodies],revision:w.revision,consumed:w.consumedRevision,bodies:w.bodies(),chunks:[...w.chunks],count:w.count,n:w.n});
function equal(a,b){assert.deepEqual(state(b),state(a));}
function patches(a,b,full=false){equal(a,b);assert.equal(JSON.stringify(b.consumeChanges({full})),JSON.stringify(a.consumeChanges({full})));equal(a,b);}
function frame(a,b,full=false){assert.equal(JSON.stringify(b.frame({full})),JSON.stringify(a.frame({full})));equal(a.world,b.world);}
function tick(a,b){assert.equal(b.step(),a.step());frame(a,b);assert.equal(b.awaitingPresentation,a.awaitingPresentation);if(a.awaitingPresentation){assert.equal(b.completePresentation(a.presentedToken+1),a.completePresentation(a.presentedToken+1));equal(a.world,b.world);}}
test('empty world, additions, deletions, empty slots, generation reuse and insertion order',()=>{const a=new Before(),b=new After();patches(a,b,true);const points=[{x:LEFT+2,y:FLOOR-1,color:2},{x:LEFT+8,y:FLOOR-1,color:2},{x:LEFT+4,y:FLOOR-1,color:2}];const r=a.addMany(points,{batch:7}),s=b.addMany(points,{batch:7});assert.deepEqual(s,r);patches(a,b);for(const w of [a,b])w.remove([r.addedIds[1]]);patches(a,b);for(const w of [a,b])w.addMany([{x:LEFT+12,y:FLOOR-1,color:3}],{batch:9});patches(a,b,true);assert.deepEqual([...b.cache.keys()],[r.addedIds[0],r.addedIds[2],b.live.length+r.addedIds[1]]);for(const w of [a,b])w.remove([...w.cache.keys()]);patches(a,b);assert.equal(b.cache.size,0);});
test('sleep and wake changes preserve revision, changedBodies and stable object reuse',()=>{const a=new Before(),b=new After();for(const w of [a,b])w.addMany([{x:LEFT+5,y:FLOOR-1,color:1}]);patches(a,b);for(const w of [a,b]){w.chunks.clear();w.sync();}patches(a,b);assert.equal([...b.cache.values()][0].sleep,true);const old=[...b.cache.values()][0],rev=b.revision;for(const w of [a,b])w.sync();patches(a,b);assert.equal([...b.cache.values()][0],old);assert.equal(b.revision,rev);for(const w of [a,b]){w.wake(5,FLOOR-1);w.sync();}patches(a,b);assert.equal([...b.cache.values()][0].sleep,false);});
test('typed-array comparison fields, batch-only legacy semantics and full sync order',()=>{const a=new Before(),b=new After();for(const w of [a,b])w.addMany([{x:LEFT+3,y:40,color:1},{x:LEFT+4,y:40,color:1}]);patches(a,b);for(const field of ['batch','x','y','color']){for(const w of [a,b]){w[field][0]++;w.sync();}patches(a,b,true);}for(const w of [a,b]){w.remove([1]);w.sync();}patches(a,b);});
test('four natural pieces retain every frame, material path and ACK result',()=>{const a=new OldGame({seed:2026}),b=new NewGame({seed:2026});a.start();b.start();frame(a,b,true);for(let n=0;n<4;n++){assert.equal(b.move(((n%5)-2)*24),a.move(((n%5)-2)*24));if(n%3===0)assert.equal(b.rotate(),a.rotate());assert.equal(b.drop(),a.drop());frame(a,b);let guard=0;while(a.phase!=='falling'&&a.state==='playing'){assert(guard++<2000);tick(a,b);}}assert.equal(b.pieces,4);assert.equal(b.world.count,9216);});
test('clear barrier, deletion, post-clear reuse and restart retain every frame',()=>{const a=new OldGame(),b=new NewGame();for(const g of [a,b]){g.state='playing';g.active=null;g.world.addMany(Array.from({length:FIELD_WIDTH},(_,i)=>({x:LEFT+i,y:FLOOR-1,color:1})));g.added=FIELD_WIDTH;g.setPhase('settling');}frame(a,b,true);let sawFlash=false,guard=0;while(a.phase!=='falling'&&a.state==='playing'){assert(guard++<250);tick(a,b);sawFlash||=a.phase==='flash';}assert(sawFlash);assert.equal(b.rawCleared,FIELD_WIDTH);assert.equal(b.drop(),a.drop());frame(a,b);guard=0;while(a.phase!=='falling'&&a.state==='playing'){assert(guard++<2000);tick(a,b);}assert([...b.world.cache.keys()].some(id=>id>=b.world.live.length));a.reset(3);b.reset(3);frame(a,b,true);assert.equal(b.start(),a.start());assert.equal(b.drop(),a.drop());frame(a,b);tick(a,b);});
test('only adapter sync changed; material, rendering, transport and UI files byte-identical',()=>{const before=new URL('../evidence/baseline0411/',import.meta.url),after=new URL('../candidate/',import.meta.url);for(const file of fs.readdirSync(after)){if(file!=='ca-adapter.mjs')assert.equal(fs.readFileSync(new URL(file,after),'utf8'),fs.readFileSync(new URL(file,before),'utf8'));}const strip=s=>s.slice(s.indexOf('\n addMany('));assert.equal(strip(fs.readFileSync(new URL('ca-adapter.mjs',after),'utf8')),strip(fs.readFileSync(new URL('ca-adapter.mjs',before),'utf8')));});
